import type { SiteLocale } from '@evtp/type/site/locale/SiteLocale';
import type { SiteText } from '@evtp/type/site/text/SiteText';

export const SITE_TEXT: Readonly<Record<SiteLocale, SiteText>> = {
  ko: {
    brandName: 'Another',
    brandFirst: 'Ano',
    brandSecond: 'ther',
    navLabel: '주요 메뉴',
    navGame: '게임 안내',
    navDownload: '다운로드',
    navLanguage: '언어 선택',
    navMenuOpen: '메뉴 열기',
    navMenuClose: '메뉴 닫기',
    localeKo: 'KO',
    localeEn: 'EN',
    skipToContent: '본문으로 이동합니다',
    heroEyebrow: '방주 <메타트론> 오퍼레이터의 안내',
    heroTagline: '생체 신호 확인 완료. 환영합니다, 구원자님.',
    heroDescription: '저는 방주 <메타트론>의 오퍼레이터이자 인공 정령, 메피스토펠레스입니다. 이 기록은 파티 던전 게임 <Another>의 안내와 내려받기를 담고 있습니다. 구원자님과 에덴의 위기를 구하기 위한 준비이니, 천천히 확인해 주시길 바랍니다.',
    heroPrimary: '내려받기',
    heroSecondary: '게임 안내',
    heroScroll: '아래를 확인합니다',
    featureEyebrow: '게임 안내',
    featureTitle: 'V0.0.1 알파 테스트에서 할 수 있는 것',
    featureDescription: '이번 빌드에서는 캐릭터 감상과 연습장이 열려 있습니다. 맵과 던전은 아직 작업 중입니다.',
    feature: [
      { index: '01', title: '캐릭터 감상', body: '로비에서 정령을 3D로 둘러보고, 터치에 반응하는 모습을 볼 수 있습니다.' },
      { index: '02', title: '연습장', body: '연습장에서 정령의 스킬을 직접 써 보며 확인할 수 있습니다.' },
      { index: '03', title: '맵과 던전', body: '맵과 던전은 아직 작업 중입니다. 준비가 끝나는 대로 업데이트로 열립니다.' },
      { index: '04', title: '그래픽 처리', body: '화면은 DirectX 12(Direct3D 12)로 그리고, 캐릭터 움직임과 파티클 계산은 NVIDIA 그래픽카드의 CUDA로 처리합니다. 그래서 NVIDIA 그래픽카드가 필요합니다.' },
      { index: '05', title: '지원 환경', body: 'Windows 10·11(64비트)에서만 실행됩니다. Linux와 macOS에서는 아직 실행되지 않습니다.' },
    ],
    downloadEyebrow: '내려받기',
    downloadTitle: '구원자님, 설치를 준비했습니다.',
    downloadDescription: '지금은 Windows에서만 실행됩니다. Linux와 macOS는 아직 지원하지 않습니다.',
    platformLabel: {
      windows: 'Windows',
      linux: 'Linux',
      macos: 'macOS',
    },
    platformSupported: '지원',
    platformUnsupported: '지원하지 않음',
    downloadCurrent: '현재 버전',
    downloadLatest: '내려받기',
    downloadPatchFiles: '패치 파일 {count}개 · {size}',
    downloadNoRelease: '아직 게시된 릴리스가 없습니다. 준비가 끝나는 대로 이 페이지에 올라갑니다.',
    downloadNotesLabel: '패치 노트',
    downloadSizeLabel: '배포본 크기',
    downloadArchiveLabel: '배포 파일',
    downloadRedirectNote: '내려받기를 누르면 GitHub 릴리스에서 zip 파일을 받습니다. 압축을 풀고 ev_launcher.exe를 실행하면 런처가 게임 데이터(약 4.2 GB)를 내려받아 설치합니다. 설치가 끝나면 게임 시작을 누르십시오.',
    downloadPrevious: '이전 릴리스',
    utilityTitle: '실행에 필요한 준비물',
    utilityDescription: 'Another를 실행하려면 아래 구성 요소가 필요합니다. 없는 항목만 공식 링크에서 설치해 주십시오.',
    utilityRequired: '필수',
    utility: [
      { id: 'directx', label: 'DirectX 12', note: 'Windows 10·11에 포함되어 있어 따로 설치하는 파일이 없습니다. Windows 업데이트를 최신으로 유지해 주십시오.' },
      { id: 'nvidia', label: 'NVIDIA 그래픽 드라이버', note: 'NVIDIA 그래픽카드(GeForce GTX 16·RTX 20 시리즈 이상)와 최신 드라이버가 필요합니다.' },
      { id: 'webview2', label: 'Microsoft Edge WebView2 런타임', note: '게임 화면과 메뉴를 표시하는 데 필요합니다. Windows 11에는 기본으로 들어 있습니다.' },
      { id: 'vcredist', label: 'Visual C++ 재배포 패키지 (x64)', note: '배포 파일에 함께 들어 있어 보통은 설치하지 않아도 됩니다.' },
    ],
    specEyebrow: '필요 사양',
    specTitle: '실행 전에 확인해 주십시오',
    spec: [
      { label: '운영체제', value: 'Windows 10·11 (64비트). Linux·macOS는 지원하지 않음' },
      { label: '그래픽', value: 'DirectX 12(셰이더 모델 6.6) 지원 NVIDIA GeForce GTX 16·RTX 20 시리즈 이상' },
      { label: '드라이버', value: '최신 NVIDIA 그래픽 드라이버' },
      { label: '저장 공간', value: '약 4.3 GB (게임 데이터 약 4.2 GB 포함)' },
      { label: '인터넷', value: '처음 설치할 때 게임 데이터를 내려받는 데 필요' },
      { label: '실행', value: '런처(ev_launcher.exe)로 실행, 항상 전체화면' },
      { label: '버전', value: 'V0.0.1 알파 테스트' },
    ],
    footerLine: '구원자와 정령이 함께 걷는, 끝나지 않는 이야기.',
    footerNavLabel: '안내 바로가기',
    footerBack: '맨 위로',
    footerBackArrow: '↑',
    footerCopyright: '© 2026 ANOTHER',
  },
  en: {
    brandName: 'Another',
    brandFirst: 'Ano',
    brandSecond: 'ther',
    navLabel: 'Main menu',
    navGame: 'Game',
    navDownload: 'Download',
    navLanguage: 'Choose language',
    navMenuOpen: 'Open menu',
    navMenuClose: 'Close menu',
    localeKo: 'KO',
    localeEn: 'EN',
    skipToContent: 'Skip to content',
    heroEyebrow: 'A BRIEFING FROM THE ARK "METATRON" OPERATOR',
    heroTagline: 'Vital sign check completed. Welcome, Savior.',
    heroDescription: 'I am the operator of the Ark "Metatron," an artificial Soul named Mephistopheles. This record holds the guide and download for the party dungeon game <Another>. Consider it preparation for the crisis facing you and Eden, and take your time.',
    heroPrimary: 'Download',
    heroSecondary: 'About the game',
    heroScroll: 'Review below',
    featureEyebrow: 'THE GAME',
    featureTitle: 'What you can do in the V0.0.1 alpha test',
    featureDescription: 'This build opens character viewing and the practice arena. Maps and dungeons are still in progress.',
    feature: [
      { index: '01', title: 'Character viewing', body: 'Look around the Souls in 3D in the lobby and watch how they react to your touch.' },
      { index: '02', title: 'Practice arena', body: 'Try out each Soul\'s skills yourself in the practice arena.' },
      { index: '03', title: 'Maps and dungeons', body: 'Maps and dungeons are still in progress. They will open in updates once they are ready.' },
      { index: '04', title: 'Graphics', body: 'The screen is drawn with DirectX 12 (Direct3D 12), and character motion and particles are computed with CUDA on an NVIDIA graphics card, so an NVIDIA graphics card is required.' },
      { index: '05', title: 'Platforms', body: 'Runs only on Windows 10 and 11 (64-bit). It does not run on Linux or macOS yet.' },
    ],
    downloadEyebrow: 'DOWNLOAD',
    downloadTitle: 'Savior, the installation is prepared.',
    downloadDescription: 'Another runs only on Windows today. Linux and macOS are not supported yet.',
    platformLabel: {
      windows: 'Windows',
      linux: 'Linux',
      macos: 'macOS',
    },
    platformSupported: 'Supported',
    platformUnsupported: 'Not supported',
    downloadCurrent: 'Current version',
    downloadLatest: 'Download',
    downloadPatchFiles: '{count} patch files · {size}',
    downloadNoRelease: 'No release has been published yet. It will appear on this page as soon as it is ready.',
    downloadNotesLabel: 'Patch notes',
    downloadSizeLabel: 'Archive size',
    downloadArchiveLabel: 'Archive',
    downloadRedirectNote: 'Download gets the zip file from the GitHub release. Unzip it and run ev_launcher.exe; the launcher downloads and installs the game data (about 4.2 GB). When it finishes, press Start Game.',
    downloadPrevious: 'Previous releases',
    utilityTitle: 'Prerequisites to run',
    utilityDescription: 'Running Another requires the components below. Install only the ones you are missing, from the official links.',
    utilityRequired: 'Required',
    utility: [
      { id: 'directx', label: 'DirectX 12', note: 'Included in Windows 10 and 11, so there is no separate installer. Keep Windows Update current.' },
      { id: 'nvidia', label: 'NVIDIA graphics driver', note: 'Requires an NVIDIA graphics card (GeForce GTX 16 or RTX 20 series or newer) and the latest driver.' },
      { id: 'webview2', label: 'Microsoft Edge WebView2 Runtime', note: 'Required to display the game screen and menus. Windows 11 includes it.' },
      { id: 'vcredist', label: 'Visual C++ Redistributable (x64)', note: 'Included in the download, so you usually do not need to install it.' },
    ],
    specEyebrow: 'REQUIREMENTS',
    specTitle: 'Check before you run',
    spec: [
      { label: 'OS', value: 'Windows 10 or 11 (64-bit). Linux and macOS are not supported' },
      { label: 'Graphics', value: 'NVIDIA GeForce GTX 16 or RTX 20 series or newer with DirectX 12 (Shader Model 6.6)' },
      { label: 'Driver', value: 'Latest NVIDIA graphics driver' },
      { label: 'Storage', value: 'About 4.3 GB (including about 4.2 GB of game data)' },
      { label: 'Internet', value: 'Required to download the game data on first install' },
      { label: 'Launch', value: 'Started by the launcher (ev_launcher.exe), always fullscreen' },
      { label: 'Version', value: 'V0.0.1 alpha test' },
    ],
    footerLine: 'A story that never ends, walked together by Saviors and Souls.',
    footerNavLabel: 'Site links',
    footerBack: 'Back to top',
    footerBackArrow: '↑',
    footerCopyright: '© 2026 ANOTHER',
  },
};
