import type { SiteLocale } from '@evtp/type/site/locale/SiteLocale';
import type { SiteText } from '@evtp/type/site/text/SiteText';

export const SITE_TEXT: Readonly<Record<SiteLocale, SiteText>> = {
  ko: {
    brandName: 'Another',
    brandFirst: 'Ano',
    brandSecond: 'ther',
    metaDescription: 'EVT: Another는 구원자와 정령이 함께하는 파티 던전 게임입니다. 개발 초기 공개본 V0.0.1 다운로드와 설치 안내, 테스터 피드백을 반영해 준비 중인 V0.0.2 패치노트를 확인하세요.',
    navLabel: '주요 메뉴',
    navGame: '게임 안내',
    navUpdates: '패치노트',
    navRoadmap: '개발 일정',
    navGuide: '시작 안내',
    navDownload: '다운로드',
    navLanguage: '언어 선택',
    navMenuOpen: '메뉴 열기',
    navMenuClose: '메뉴 닫기',
    musicTitle: '에덴의 선율',
    musicTrack: '로비의 노래 · 02',
    musicPlay: '배경음 재생',
    musicPause: '배경음 일시정지',
    musicMute: '배경음 음소거',
    musicUnmute: '배경음 음소거 해제',
    musicSeek: '배경음 재생 위치',
    musicUnavailable: '배경음을 재생할 수 없습니다',
    localeKo: 'KO',
    localeEn: 'EN',
    skipToContent: '본문으로 이동합니다',
    heroEyebrow: '오퍼레이터 메피스토펠레스의 안내',
    heroTagline: '생체 신호 확인 완료. 환영합니다, 구원자님.',
    heroDescription: '저는 메피스토펠레스입니다. 구원자님과 정령들이 함께 에덴을 걸어갈 수 있도록 안내해 드릴게요. 처음 공개한 모습과 지금 준비하는 이야기를 이곳에 차례로 남겼습니다. 천천히 둘러봐 주세요. 케이크 한 조각이 함께해도 좋겠네요.',
    heroPrimary: '내려받기',
    heroSecondary: '게임 안내',
    heroScroll: '아래를 확인합니다',
    featureEyebrow: '게임 안내',
    featureTitle: '구원자님과 정령들의 첫걸음',
    featureSubtitle: '첫 공개본에서 만나는 플레이',
    featureDescription: 'Another는 구원자님과 정령들이 함께하는 파티 던전 게임입니다. 처음 공개한 V0.0.1은 개발 초기의 모습을 그대로 담았습니다. 지금 만나실 수 있는 공간부터 안내해 드릴게요.',
    featureReleaseLabel: 'V0.0.1 공개본',
    featurePreparingLabel: '개발 중',
    feature: [
      { index: '01', title: '정령과 만나는 로비', body: '로비에서는 정령의 모습을 가까이에서 둘러보고, 손길에 반응하는 모습도 볼 수 있습니다.', status: 'V0.0.1 공개본' },
      { index: '02', title: '함께 움직이는 연습장', body: '연습장에서 정령의 기술을 직접 사용해 보실 수 있습니다. 어떤 정령과 먼저 만나고 싶으신가요?', status: 'V0.0.1 공개본' },
      { index: '03', title: '준비 중인 여정', body: '맵과 던전은 첫 공개본에서 아직 열리지 않았습니다. 준비 상황은 아래 기록에서 계속 알려드릴게요.', status: '개발 중' },
      { index: '04', title: '정령과 파티 꾸리기', body: '현재 개발 코드에는 정령을 파티에 불러와 함께 움직이는 흐름이 연결되어 있습니다. 첫 공개본에서의 동작과는 구분해 확인하고 있습니다.', status: '현재 코드 · 검증 중' },
    ],
    updateEyebrow: '메피스토펠레스의 준비 기록',
    updateTitle: 'V0.0.2를 준비하고 있습니다',
    updateSubtitle: '코드 반영과 실제 기기 확인은 서로 다른 단계입니다',
    updateDescription: 'V0.0.1은 개발 초기 상태로 공개됐습니다. 다른 기기에서 보내주신 일곱 가지 이야기를 하나씩 살피고 있습니다. 지금 말씀드릴 수 있는 건 코드에서 확인한 내용까지예요. 실제 기기에서의 해결은 아직 확인이 필요합니다.',
    updatePatchTitle: 'V0.0.2 패치노트 초안',
    updatePatchCaution: '아래 변화는 코드에 연결된 내용입니다. 구원자님의 기기에서도 잘 작동하는지 확인한 뒤에야 해결됐다고 말씀드릴 수 있어요.',
    updateJump: '개발 일정 살펴보기',
    roadmapEyebrow: '개발 일정',
    roadmapTitle: '일곱 가지 이야기를 따라가 볼까요?',
    roadmapSubtitle: '제보 일곱 건의 현재 위치',
    roadmapDescription: '구원자님이 남겨주신 이야기를 현재 확인 단계에 따라 놓았습니다. 날짜를 약속하기보다는, 원인을 찾고 기기에서 확인하고 기능을 잇는 과정을 정직하게 전해드릴게요.',
    roadmapCountUnit: '건',
    roadmapJump: '패치노트 다시 보기',
    roadmapReport: '새 이슈 제보하기',
    issueFeedTitle: '지금 올라온 제보',
    issueFeedDescription: 'GitHub에 공개된 제보를 상태와 날짜별로 확인하실 수 있습니다.',
    issueFeedEmpty: '이 목록에 표시할 이슈가 없습니다.',
    issueFeedFilterLabel: '이슈 목록 선택',
    issueFeedAll: '전체',
    issueFeedOpen: '진행 중',
    issueFeedClosed: '종료',
    issueFeedNumberLabel: '번호',
    issueFeedSubjectLabel: '제목',
    issueFeedStatusLabel: '상태',
    issueFeedDateLabel: '최근 수정',
    issueFeedPagesLabel: '이슈 목록 페이지',
    issueFeedPrevious: '이전',
    issueFeedNext: '다음',
    roadmapStages: [
      { id: 'investigating', title: '원인을 찾는 중', description: '어긋나는 지점을 먼저 확인하고 있습니다.' },
      { id: 'verifying', title: '직접 확인 대기', description: '코드에 연결된 변화가 제보 기기에서도 맞는지 살핍니다.' },
      { id: 'connecting', title: '기능을 잇는 중', description: '아직 이어지지 않은 기능을 완성해야 합니다.' },
    ],
    updateEntries: [
      { id: 'T-A1', title: '일부 기기에서 게임이 바로 종료돼요', status: '원인 확인 중', stage: 'investigating', body: 'AMD 그래픽카드에서는 NVIDIA 전용 계산을 시작하지 않도록 코드가 나뉘었습니다. 다만 제보받은 종료 지점은 기록이 없어 아직 특정하지 못했습니다.', patchNote: 'AMD 그래픽카드에서 NVIDIA 전용 계산을 시도하지 않도록 경로를 분리했습니다.' },
      { id: 'T-B1', title: '게임을 열 수 없는 기기가 있어요', status: '기기 확인 대기', stage: 'verifying', body: '첫 화면 방식이 맞지 않으면 다른 방식을 살피는 코드가 연결됐습니다. 제보받은 기기에서 실제로 열리는지는 다시 확인해야 합니다.', patchNote: '기기에 맞는 화면 방식을 차례로 선택하는 경로를 연결했습니다.' },
      { id: 'T-C1', title: '화면 크기가 모니터와 맞지 않아요', status: '기기 확인 대기', stage: 'verifying', body: '모니터의 현재 화면 크기를 기본으로 읽고, 선택할 수 있는 크기를 설정에 반영하는 코드가 있습니다. 제보받은 모니터에서의 결과는 아직 확인 전입니다.', patchNote: '현재 모니터 크기를 기본값으로 쓰고, 선택 가능한 화면 크기를 설정에 연결했습니다.' },
      { id: 'T-C2', title: '장소가 바뀌어도 로비 음악이 들려요', status: '소리 확인 대기', stage: 'verifying', body: '로비를 떠날 때 음악을 멈추고 새 장소의 음악을 따로 재생하는 코드가 연결됐습니다. 실제 전환 소리는 다시 들어봐야 합니다.', patchNote: '로비 음악을 멈추는 시점과 장소별 음악 재생을 분리했습니다.' },
      { id: 'T-C3', title: '공격할 때 시선과 움직임이 어색해요', status: '원인 확인 중', stage: 'investigating', body: '조준한 곳과 머리 움직임이 이어지는 코드는 확인했습니다. 어느 순간 방향이 어긋나는지는 아직 찾지 못했습니다.' },
      { id: 'T-C4', title: '적과 싸울 수 없어요', status: '아직 연결 전', stage: 'connecting', body: '적의 공격과 피격은 아직 이어지지 않았습니다. 지금 단계에서 작동한다고 안내드릴 수 없는 기능입니다.' },
      { id: 'T-C5', title: '영지 계단에서 아래로 빠져요', status: '원인 확인 중', stage: 'investigating', body: '걷는 땅과 계단의 높이를 살피는 코드가 있지만, 제보하신 계단에서 어디서 발을 헛디디는지는 아직 확인하지 못했습니다.' },
    ],
    guideEyebrow: '시작 안내',
    guideTitle: '처음 오셨군요, 구원자님',
    guideSubtitle: '첫 실행은 네 단계로 안내해 드릴게요',
    guideDescription: '지금 내려받을 수 있는 것은 첫 공개본 V0.0.1입니다. 설치 순서는 네 단계예요. 제가 곁에서 안내해 드리겠습니다.',
    guideSteps: [
      { index: '01', title: '파일을 받아 압축을 풀어 주세요', body: '아래 다운로드에서 V0.0.1 압축 파일을 받으신 뒤, 원하는 위치에 풀어 주세요.' },
      { index: '02', title: '런처를 열어 주세요', body: '압축을 푼 폴더에서 ev_launcher.exe를 실행해 주세요.' },
      { index: '03', title: '설치를 눌러 주세요', body: '처음에는 게임 자료를 받아야 합니다. 빨간 설치 버튼을 누르면 진행 상황을 확인하실 수 있어요.' },
      { index: '04', title: '게임 시작을 눌러 주세요', body: '설치가 끝나면 게임 시작을 눌러 주세요. 이제 정령들이 구원자님을 기다리고 있습니다.' },
    ],
    mephistoSceneTitle: '제가 곁에서 안내해 드릴게요',
    mephistoPanelTitle: '말을 골라 주세요',
    mephistoLoading: '메피스토펠레스를 부르고 있습니다…',
    mephistoUnavailable: '3D 모습을 불러오지 못했습니다. 아래의 음성과 안내는 계속 이용하실 수 있습니다.',
    mephistoVoiceUnavailable: '음성을 재생하지 못했습니다. 대사는 아래에서 읽으실 수 있습니다.',
    mephistoVoiceNote: '원본 한국어 음성 · 대사는 선택한 언어로 표시됩니다.',
    mephistoOpen: '메피스토펠레스 안내 열기',
    mephistoClose: '메피스토펠레스 안내 접기',
    mephistoDragHint: '메피스토펠레스 위치 이동. 드래그하거나 방향키로 옮기고, 짧게 누르면 반응합니다.',
    mephistoMessages: {
      top: '구원자님, 어서 오세요. 제가 곁에서 안내해 드릴게요.',
      features: '먼저 정령들과 만날 수 있는 곳부터 둘러보실까요?',
      updates: 'V0.0.2의 준비 기록입니다. 아직 해결됐다고 말씀드릴 단계는 아니에요.',
      roadmap: '일곱 가지 제보가 지금 어디에 있는지 함께 살펴봐요.',
      guide: '처음 오셨군요. 네 단계를 따라오시면 됩니다.',
      download: '현재 내려받을 수 있는 것은 첫 공개본 V0.0.1이에요.',
      specs: '실행 전에 필요한 사양도 확인해 주세요.',
      lounge: '열정페이로 같이 만들고 싶은 바이브코더, 모델러, 어떤 기여자든 환영합니다.',
    },
    mephistoReactions: {
      greeting: { label: '인사 듣기', caption: '구원자님, 어서 오세요.' },
      touch: { label: '고양이 이야기', caption: '아케나인의 삼색 고양이들과 얼룩 고양이들은 사이가 나빠요. 이유가 뭘까요. 주목할 만한 현상입니다.' },
      touchsp: { label: '놀란 반응', caption: '아…' },
      touchsp02: { label: '다정한 반응', caption: '구원자님, 안아드려도 될까요? 그러고 싶어요.' },
    },
    downloadEyebrow: '내려받기',
    downloadTitle: '첫 공개본을 내려받으세요',
    downloadSubtitle: 'V0.0.1 공개 · V0.0.2 준비 중',
    downloadDescription: 'V0.0.1은 Windows에서만 실행됩니다. Linux와 macOS에서는 아직 만나 뵐 수 없어요.',
    platformLabel: {
      windows: 'Windows',
      linux: 'Linux',
      macos: 'macOS',
    },
    platformSupported: '지원',
    platformUnsupported: '지원하지 않음',
    downloadCurrent: '내려받을 수 있는 버전',
    downloadLatest: '내려받기',
    downloadPatchFiles: '패치 파일 {count}개 · {size}',
    downloadNoRelease: '아직 게시된 릴리스가 없습니다. 준비가 끝나는 대로 이 페이지에 올라갑니다.',
    downloadNotesLabel: '패치 노트',
    downloadSizeLabel: '배포본 크기',
    downloadArchiveLabel: '배포 파일',
    downloadRedirectNote: '내려받기를 누르면 GitHub에서 압축 파일을 받습니다. 압축을 풀고 런처를 실행해 주세요. 처음에는 게임 자료를 추가로 받으니, 설치가 끝날 때까지 기다려 주시면 됩니다.',
    downloadPrevious: '이전 릴리스',
    utilityTitle: '실행에 필요한 준비물',
    utilityDescription: '게임을 여는 데 필요한 준비물입니다. 없는 항목만 공식 안내에서 받아 주세요.',
    utilityRequired: '필수',
    utility: [
      { id: 'directx', label: 'DirectX 12', note: 'Windows 10·11에 포함되어 있어 따로 설치하는 파일이 없습니다. Windows 업데이트를 최신으로 유지해 주십시오.' },
      { id: 'nvidia', label: 'NVIDIA 그래픽 드라이버', note: 'NVIDIA 그래픽카드(GeForce GTX 16·RTX 20 시리즈 이상)와 최신 드라이버가 필요합니다.' },
      { id: 'webview2', label: 'Microsoft Edge WebView2 런타임', note: '게임 화면과 메뉴를 표시하는 데 필요합니다. Windows 11에는 기본으로 들어 있습니다.' },
      { id: 'vcredist', label: 'Visual C++ 재배포 패키지 (x64)', note: '배포 파일에 함께 들어 있어 보통은 설치하지 않아도 됩니다.' },
    ],
    specEyebrow: '필요 사양',
    specTitle: '실행 전에 확인해 주십시오',
    specRecommendedTitle: '권장 사양',
    specRecommendedBody: '권장 사양은 아직 실제 기기에서 측정해 확정하지 않았습니다. 위 항목은 V0.0.1 첫 공개본의 실행 요구 사항이며, 제보 기기에서의 결과는 계속 확인하고 있습니다.',
    spec: [
      { label: '운영체제', value: 'Windows 10·11 (64비트). Linux·macOS는 지원하지 않음' },
      { label: '그래픽', value: 'DirectX 12(셰이더 모델 6.6) 지원 NVIDIA GeForce GTX 16·RTX 20 시리즈 이상' },
      { label: '드라이버', value: '최신 NVIDIA 그래픽 드라이버' },
      { label: '저장 공간', value: '약 4.3 GB (게임 데이터 약 4.2 GB 포함)' },
      { label: '인터넷', value: '처음 설치할 때 게임 데이터를 내려받는 데 필요' },
      { label: '실행', value: '런처(ev_launcher.exe)로 실행, 항상 전체화면' },
      { label: '버전', value: 'V0.0.1 알파 테스트' },
    ],
    loungeEyebrow: '함께 만드는 Another',
    loungeTitle: '개발자 구인 라운지',
    loungeInvite: '열정페이로 같이 만들고 싶은 바이브코더, 모델러, 어떤 기여자든 환영합니다.',
    loungeFlowLabel: '제작 흐름',
    loungeFlow: ['원본 자료', '에셋 생산·카탈로그', '게임 엔진·클라이언트', '릴리즈'],
    loungeStackLabel: '실제 개발 스택',
    loungeStack: ['C++26', 'SDL3', 'TypeScript', 'SolidJS', 'three.js', 'Direct3D 12', 'Direct3D 11', 'xmake'],
    footerLine: '구원자와 정령이 함께 걷는, 끝나지 않는 이야기.',
    footerNavLabel: '안내 바로가기',
    footerReport: '이슈 신고',
    footerBack: '맨 위로',
    footerBackArrow: '↑',
    footerCopyright: '© 2026 ANOTHER',
  },
  en: {
    brandName: 'Another',
    brandFirst: 'Ano',
    brandSecond: 'ther',
    metaDescription: 'EVT: Another is a party dungeon game with the Savior and the Souls. Download the early V0.0.1 release, follow the installation guide, and read the V0.0.2 patch notes draft based on tester feedback.',
    navLabel: 'Main menu',
    navGame: 'Game',
    navUpdates: 'Patch notes',
    navRoadmap: 'Roadmap',
    navGuide: 'Getting started',
    navDownload: 'Download',
    navLanguage: 'Choose language',
    navMenuOpen: 'Open menu',
    navMenuClose: 'Close menu',
    musicTitle: 'Melody of Eden',
    musicTrack: 'Lobby melody · 02',
    musicPlay: 'Play background music',
    musicPause: 'Pause background music',
    musicMute: 'Mute background music',
    musicUnmute: 'Unmute background music',
    musicSeek: 'Background music position',
    musicUnavailable: 'Background music is unavailable',
    localeKo: 'KO',
    localeEn: 'EN',
    skipToContent: 'Skip to content',
    heroEyebrow: 'A NOTE FROM OPERATOR MEPHISTOPHELES',
    heroTagline: 'Vital sign check completed. Welcome, Savior.',
    heroDescription: 'I am Mephistopheles. I will help you and the Souls find your way through Eden. I have kept the story of our first release and what we are preparing here for you. Please take your time. A slice of cake would be nice, too.',
    heroPrimary: 'Download',
    heroSecondary: 'About the game',
    heroScroll: 'Review below',
    featureEyebrow: 'THE GAME',
    featureTitle: 'Your first steps with the Souls',
    featureSubtitle: 'What you can play in the first release',
    featureDescription: 'Another is a party dungeon game about you and the Souls. V0.0.1 was shared in its early development state. Let me show you the places you can visit in that first release.',
    featureReleaseLabel: 'In V0.0.1',
    featurePreparingLabel: 'In development',
    feature: [
      { index: '01', title: 'Meet the Souls in the lobby', body: 'You can look closely at the Souls in the lobby and see how they respond to your touch.', status: 'In V0.0.1' },
      { index: '02', title: 'Try the practice arena', body: 'You can try the Souls\' skills for yourself. Who would you like to meet first?', status: 'In V0.0.1' },
      { index: '03', title: 'A journey still taking shape', body: 'Maps and dungeons were not open in the first release. I will keep you informed in the notes below.', status: 'In development' },
      { index: '04', title: 'Bring a Soul into your party', body: 'The current development code connects Souls to a moving party. We are checking this separately from the first public release.', status: 'Current code · verifying' },
    ],
    updateEyebrow: 'A RECORD FOR YOU, SAVIOR',
    updateTitle: 'We are preparing V0.0.2',
    updateSubtitle: 'Code changes and device results are separate steps',
    updateDescription: 'V0.0.1 went out in its early development state. We are going through seven reports sent from other devices, one by one. For now, I can tell you what the code shows. The results on those devices still need to be checked.',
    updatePatchTitle: 'V0.0.2 patch notes draft',
    updatePatchCaution: 'These changes are present in the code. I will call them resolved only after we have checked them on your devices.',
    updateJump: 'Explore the roadmap',
    roadmapEyebrow: 'ROADMAP',
    roadmapTitle: 'Follow the seven reports with me',
    roadmapSubtitle: 'The current stage of seven reports',
    roadmapDescription: 'I have placed your reports by the step each one is at. I will share the work of finding causes, checking devices, and connecting features without promising dates we have not set.',
    roadmapCountUnit: ' reports',
    roadmapJump: 'Return to patch notes',
    roadmapReport: 'Report an issue',
    issueFeedTitle: 'Reports from the community',
    issueFeedDescription: 'Browse public GitHub reports by status and date.',
    issueFeedEmpty: 'There are no issues in this list.',
    issueFeedFilterLabel: 'Choose issue list',
    issueFeedAll: 'All',
    issueFeedOpen: 'Open',
    issueFeedClosed: 'Closed',
    issueFeedNumberLabel: 'No.',
    issueFeedSubjectLabel: 'Title',
    issueFeedStatusLabel: 'Status',
    issueFeedDateLabel: 'Updated',
    issueFeedPagesLabel: 'Issue list pages',
    issueFeedPrevious: 'Previous',
    issueFeedNext: 'Next',
    roadmapStages: [
      { id: 'investigating', title: 'Finding the cause', description: 'We are looking for the point where things go wrong.' },
      { id: 'verifying', title: 'Checking devices', description: 'We need to see whether the code changes work on the reported devices.' },
      { id: 'connecting', title: 'Connecting the feature', description: 'This feature still needs to be completed.' },
    ],
    updateEntries: [
      { id: 'T-A1', title: 'The game closes at startup on some devices', status: 'Cause under review', stage: 'investigating', body: 'On AMD graphics cards, the code no longer starts calculations reserved for NVIDIA cards. We still cannot identify the exact point of the reported crash without its log.', patchNote: 'Separated the NVIDIA calculation path so AMD cards do not start it.' },
      { id: 'T-B1', title: 'Some devices cannot open the game', status: 'Device check needed', stage: 'verifying', body: 'The code can try another way to draw the screen if the first one is unavailable. We still need to see whether the reported device opens the game.', patchNote: 'Connected the path that tries available screen drawing methods in order.' },
      { id: 'T-C1', title: 'The screen size does not match the monitor', status: 'Device check needed', stage: 'verifying', body: 'The code now reads the monitor\'s current size by default and connects available sizes to settings. The result on the reported monitor has not yet been checked.', patchNote: 'Made the current monitor size the default and connected available sizes to settings.' },
      { id: 'T-C2', title: 'Lobby music continues in another place', status: 'Sound check needed', stage: 'verifying', body: 'The code stops lobby music when you leave and plays music for the new place separately. We still need to listen to the actual transition.', patchNote: 'Separated the moment lobby music stops from music played in each place.' },
      { id: 'T-C3', title: 'Looking and moving feel wrong during attacks', status: 'Cause under review', stage: 'investigating', body: 'I found the code connecting your aim to head movement. We have not yet found where the direction goes wrong.' },
      { id: 'T-C4', title: 'You cannot fight enemies', status: 'Not connected yet', stage: 'connecting', body: 'Enemy attacks and taking hits are not fully connected. I cannot tell you this feature works yet.' },
      { id: 'T-C5', title: 'You fall through the stairs in town', status: 'Cause under review', stage: 'investigating', body: 'There is code for walking surfaces and step height, but we have not yet found where you lose your footing on the reported stairs.' },
    ],
    guideEyebrow: 'GETTING STARTED',
    guideTitle: 'Welcome, Savior',
    guideSubtitle: 'Four steps to start the first release',
    guideDescription: 'V0.0.1 is the first release available to download. There are four steps. I will guide you through them.',
    guideSteps: [
      { index: '01', title: 'Download and unzip the file', body: 'Use the download below to get the V0.0.1 archive, then unzip it wherever you would like.' },
      { index: '02', title: 'Open the launcher', body: 'Run ev_launcher.exe from the unzipped folder.' },
      { index: '03', title: 'Press Install', body: 'The first launch needs to download game data. Press the red Install button and watch its progress.' },
      { index: '04', title: 'Press Start Game', body: 'Once installation finishes, press Start Game. The Souls are waiting for you.' },
    ],
    mephistoSceneTitle: 'I will guide you from here',
    mephistoPanelTitle: 'Talk to me, Savior',
    mephistoLoading: 'Calling Mephistopheles…',
    mephistoUnavailable: 'The 3D model could not be loaded. The voice and guide below are still available.',
    mephistoVoiceUnavailable: 'The voice could not be played. You can read the line below.',
    mephistoVoiceNote: 'Original Korean voice · lines appear in your selected language.',
    mephistoOpen: 'Open Mephistopheles guide',
    mephistoClose: 'Collapse Mephistopheles guide',
    mephistoDragHint: 'Move Mephistopheles. Drag or use the arrow keys; press briefly for a reaction.',
    mephistoMessages: {
      top: 'Welcome, Savior. I will stay here and guide you.',
      features: 'Shall we start with the places where you can meet the Souls?',
      updates: 'Here is our V0.0.2 record. The reports are not confirmed resolved yet.',
      roadmap: 'Let us see where each of the seven reports stands.',
      guide: 'Your first visit? Follow these four steps with me.',
      download: 'V0.0.1 is the first release you can download today.',
      specs: 'Please check the requirements before starting.',
      lounge: 'Vibe coders, modelers, and anyone who wants to create together for passion pay are welcome.',
    },
    mephistoReactions: {
      greeting: { label: 'Hear a greeting', caption: 'Welcome, Savior.' },
      touch: { label: 'A cat story', caption: 'In Arkenine, tricolor cats are in bad terms with tabby cats. I wonder why. This is a notable phenomenon.' },
      touchsp: { label: 'A surprised reaction', caption: 'Oh…' },
      touchsp02: { label: 'A warm reaction', caption: 'Savior, may I give you a hug? I just feel like hugging you.' },
    },
    downloadEyebrow: 'DOWNLOAD',
    downloadTitle: 'Download the first release',
    downloadSubtitle: 'V0.0.1 available · V0.0.2 in preparation',
    downloadDescription: 'V0.0.1 runs only on Windows. We cannot meet on Linux or macOS yet.',
    platformLabel: {
      windows: 'Windows',
      linux: 'Linux',
      macos: 'macOS',
    },
    platformSupported: 'Supported',
    platformUnsupported: 'Not supported',
    downloadCurrent: 'Available version',
    downloadLatest: 'Download',
    downloadPatchFiles: '{count} patch files · {size}',
    downloadNoRelease: 'No release has been published yet. It will appear on this page as soon as it is ready.',
    downloadNotesLabel: 'Patch notes',
    downloadSizeLabel: 'Archive size',
    downloadArchiveLabel: 'Archive',
    downloadRedirectNote: 'Download gets the archive from GitHub. Please unzip it and open the launcher. It needs to download more game data on the first run, so please wait until installation finishes.',
    downloadPrevious: 'Previous releases',
    utilityTitle: 'Prerequisites to run',
    utilityDescription: 'These are the things you need to open the game. Please use the official links for anything you are missing.',
    utilityRequired: 'Required',
    utility: [
      { id: 'directx', label: 'DirectX 12', note: 'Included in Windows 10 and 11, so there is no separate installer. Keep Windows Update current.' },
      { id: 'nvidia', label: 'NVIDIA graphics driver', note: 'Requires an NVIDIA graphics card (GeForce GTX 16 or RTX 20 series or newer) and the latest driver.' },
      { id: 'webview2', label: 'Microsoft Edge WebView2 Runtime', note: 'Required to display the game screen and menus. Windows 11 includes it.' },
      { id: 'vcredist', label: 'Visual C++ Redistributable (x64)', note: 'Included in the download, so you usually do not need to install it.' },
    ],
    specEyebrow: 'REQUIREMENTS',
    specTitle: 'Check before you run',
    specRecommendedTitle: 'Recommended requirements',
    specRecommendedBody: 'Recommended hardware has not yet been measured and confirmed on real devices. The list above describes the first V0.0.1 release requirements; results on reported devices still need checking.',
    spec: [
      { label: 'OS', value: 'Windows 10 or 11 (64-bit). Linux and macOS are not supported' },
      { label: 'Graphics', value: 'NVIDIA GeForce GTX 16 or RTX 20 series or newer with DirectX 12 (Shader Model 6.6)' },
      { label: 'Driver', value: 'Latest NVIDIA graphics driver' },
      { label: 'Storage', value: 'About 4.3 GB (including about 4.2 GB of game data)' },
      { label: 'Internet', value: 'Required to download the game data on first install' },
      { label: 'Launch', value: 'Started by the launcher (ev_launcher.exe), always fullscreen' },
      { label: 'Version', value: 'V0.0.1 alpha test' },
    ],
    loungeEyebrow: 'CREATE ANOTHER TOGETHER',
    loungeTitle: 'Developer lounge',
    loungeInvite: 'Vibe coders, modelers, and anyone who wants to create together for passion pay are welcome.',
    loungeFlowLabel: 'Production flow',
    loungeFlow: ['Original assets', 'Asset production & catalog', 'Game engine & client', 'Release'],
    loungeStackLabel: 'Development stack',
    loungeStack: ['C++26', 'SDL3', 'TypeScript', 'SolidJS', 'three.js', 'Direct3D 12', 'Direct3D 11', 'xmake'],
    footerLine: 'A story that never ends, walked together by Saviors and Souls.',
    footerNavLabel: 'Site links',
    footerReport: 'Report an issue',
    footerBack: 'Back to top',
    footerBackArrow: '↑',
    footerCopyright: '© 2026 ANOTHER',
  },
};
