import type { SiteLocale } from '@evtp/type/site/locale/SiteLocale';
import type { SiteText } from '@evtp/type/site/text/SiteText';

export const SITE_TEXT: Readonly<Record<SiteLocale, SiteText>> = {
  ko: {
    brandName: 'Another',
    brandFirst: 'Ano',
    brandSecond: 'ther',
    metaDescription: 'EVT: Another는 구원자와 정령이 함께하는 파티 던전 게임입니다. 지금 작동하는 콘텐츠와 V0.0.2 개발 방향 공지 13가지의 구현 상태, 다음 V0.0.3 일정, 공개된 V0.0.1 다운로드 안내를 확인하세요.',
    navLabel: '주요 메뉴',
    navGame: '게임 안내',
    navUpdates: '패치노트',
    navRoadmap: '개발 일정',
    navGuide: '시작 안내',
    navDownload: '다운로드',
    navLanguage: '언어 선택',
    navMenuOpen: '메뉴 열기',
    navMenuClose: '메뉴 닫기',
    musicTitle: '에덴의 선율',
    musicTrack: '로비의 노래 · 02',
    musicPlay: '배경음 재생',
    musicPause: '배경음 일시정지',
    musicMute: '배경음 음소거',
    musicUnmute: '배경음 음소거 해제',
    musicSeek: '배경음 재생 위치',
    musicUnavailable: '배경음을 재생할 수 없습니다',
    localeKo: 'KO',
    localeEn: 'EN',
    skipToContent: '본문으로 이동합니다',
    heroEyebrow: '오퍼레이터 메피스토펠레스의 안내',
    heroTagline: '생체 신호 확인 완료. 환영합니다, 구원자님.',
    heroDescription: '저는 메피스토펠레스입니다. 구원자님과 정령들이 함께 에덴을 걸어갈 수 있도록 안내해 드릴게요. 처음 공개한 모습과 지금 준비하는 이야기를 이곳에 차례로 남겼습니다. 천천히 둘러봐 주세요. 케이크 한 조각이 함께해도 좋겠네요.',
    heroPrimary: '내려받기',
    heroSecondary: '게임 안내',
    heroScroll: '아래를 확인합니다',
    heroDevNotice: '본격적인 전투 메커니즘과 정령 육성 방향, 게임 콘텐츠 전반은 아직 설계를 준비하고 있어요. 지금은 원본 게임의 기능을 그대로 재현하는 일을 가장 먼저 하고 있습니다.',
    heroDevLink: 'DEV 공지 자세히 보기',
    featureEyebrow: '게임 안내',
    featureTitle: '정령과 함께 시작하는 모험',
    featureSubtitle: '로비·영지·던전부터 소환과 감상까지, 지금 작동하는 콘텐츠',
    featureDescription: 'Another는 정령과 팀을 이뤄 에덴을 모험하는 파티 던전 게임입니다. 아래에는 현재 V0.0.2 게임 코드에서 작동하는 콘텐츠와 그 기능을 하나씩 적었습니다. 공개 다운로드 V0.0.1에서는 로비와 연습장을 즐기실 수 있습니다.',
    featureStage: {
      release: 'V0.0.1부터',
      current: 'V0.0.2',
    },
    devNoticeLabel: 'DEV 공지',
    devNoticeTitle: '지금은 원본 기능의 재현을 먼저 합니다',
    devNoticeBody: '본격적인 전투 메커니즘, 정령 육성 방향, 게임 콘텐츠 전반은 아직 설계를 준비하고 있습니다. 지금은 원본 게임의 화면·움직임·연출·소리를 이 엔진에서 그대로 되살리는 "기능 재현"을 가장 먼저 하고 있습니다.',
    devNoticeItems: [
      '전투: 정령의 공격·스킬 동작과 몬스터의 체력·피격 동작은 있지만, 피해를 주고받는 전투 규칙은 아직 설계 중입니다. 레이드 보스는 원본 위치와 크기로 서 있고 공격하지 않습니다.',
      '육성: 정령을 키우는 방향은 아직 정하지 않았습니다. 지금의 테스트 빌드는 개발 모드가 기본으로 켜져 있어 모든 정령이 해금되고 소환과 구매가 무제한이며, 환경설정에서 끌 수 있습니다.',
      '보상: 던전의 코인과 레이드의 특별 티켓은 화면 안내만 있고, 실제 보상은 전투를 설계하면서 연결합니다.',
      '콘텐츠: 메인 스토리·인연 스토리·던전 원본 맵을 모을 오리진 메뉴와 영지 건물 설치, 월드 에디터는 그다음에 설계합니다.',
    ],
    feature: [
      {
        index: '01', title: '구원자의 공간, 로비', stage: 'release',
        body: '정령을 로비에 세워 가까이 감상합니다. 파티를 모두 세우거나 도감에서 고른 정령 한 명만 세울 수 있습니다.',
        items: [
          '클릭으로 터치하면 정령이 반응하고, 스페셜 터치 대사가 있는 정령은 스페셜 터치로 또 다른 반응을 보여 줍니다.',
          '자유 이동으로 로비를 직접 걸어 다니고, 감상 모드로 언제든 돌아옵니다.',
          '자유 카메라에서 이동·상승·하강·드래그 회전으로 구도를 잡습니다. 룩앳을 켜면 정령이 카메라를 바라보고, 바닥을 클릭하면 그 자리로 걸어갑니다.',
          '사진 모드와 인터페이스 숨기기로 장면만 남길 수 있습니다.',
          'BGM 플레이어에서 기본·스토리·정령·이벤트 곡을 골라 듣고 플레이리스트를 만듭니다. 좋아요를 누른 곡은 맵과 메뉴를 옮겨도 계속 재생됩니다.',
        ],
      },
      {
        index: '02', title: '정령 도감과 크게 보기', stage: 'current',
        body: '수집한 정령을 이름으로 찾고 전체·보유·파티로 나눠 봅니다.',
        items: [
          '정령마다 프로필·소개·스킨·스킬·능력치를 살펴봅니다.',
          '크게 보기는 자유 카메라와 같은 화면과 조작을 제공하며, 룩앳과 바닥 클릭 이동도 같습니다.',
          '무기·마스크 파츠 표시를 켜고 끄며, 이동 방식은 원본 유지와 걷기 보정 중에서 고릅니다. 탈것을 타는 정령은 탈것도 켜고 끌 수 있습니다.',
          '파티에 합류시키거나 동행을 해제하고, 로비에서 바로 볼 수 있습니다.',
        ],
      },
      {
        index: '03', title: '정령 소환과 원본 소환 연출', stage: 'current',
        body: '티켓으로 정령을 소환해 도감을 채우고 파티에 합류시킵니다.',
        items: [
          '정령 소환은 모든 정령이 같은 확률이고, 특별 소환은 아직 모으지 않은 정령 중에서 소환합니다. 모두 모았다면 전체 정령 중에서 소환합니다.',
          '1회·10회 소환, 소환 확률 보기, 새로운 정령과 중복 정령을 나눈 결과 목록, 다시 소환을 지원합니다.',
          '원본 소환 연출이 재생됩니다. 연출 오퍼레이터는 메피스토펠레스·벨레스·릴리스 가운데 환경설정에서 고르고, 건너뛰기 버튼이나 ESC로 넘길 수 있습니다.',
        ],
      },
      {
        index: '04', title: '상점과 보유 재화', stage: 'current',
        body: '코인으로 소환 티켓을 바꾸는 티켓 교환소가 있습니다.',
        items: [
          '소환 티켓은 1장에 1,000코인, 10장 묶음은 10,000코인이며, 수량은 한 번에 최대 99까지 고릅니다.',
          '특별 티켓은 상점에서 팔지 않으며 레이드 보상으로 준비하고 있습니다.',
          '코인·소환 티켓·특별 티켓은 게임 데이터베이스에 저장됩니다.',
        ],
      },
      {
        index: '05', title: '구원자와 정령의 파티', stage: 'current',
        body: '구원자와 정령으로 최대 4명의 파티를 편성하며, 파티에는 최소 1명이 있어야 합니다.',
        items: [
          '구원자도 파티에 합류합니다. 구원자는 기본 공격으로 싸우고, 정령과 교대하면 스킬을 씁니다.',
          '파티 창과 슬롯 키 1~4로 조작할 멤버를 바로 교대합니다.',
          '로비와 던전 목록에서 지금 파티를 확인하고 편성 화면으로 이동합니다.',
        ],
      },
      {
        index: '06', title: '연습 / 훈련장', stage: 'release',
        body: '정령의 기본 공격과 스킬 1~4를 직접 써 보며 움직임과 연출을 확인합니다.',
        items: [
          '기본 공격과 스킬을 쓰는 동안에도 움직일 수 있으며, 기본 공격 중에는 이동 속도의 0.9배, 스킬 중에는 0.3배로 움직입니다.',
          '이동·달리기·점프·공격·스킬 키는 환경설정의 단축키에서 바꿉니다.',
        ],
      },
      {
        index: '07', title: '여섯 던전 탐험', stage: 'current',
        body: '아케나인 성·수정 동굴·잊혀진 영웅의 유적·죽음굴·유물 사원·종말의 기원에 들어갈 수 있습니다.',
        items: [
          '원본 위치에 몬스터가 배치되고, 문·다리 같은 장치와 텔레포트(이동 안내와 확인 창)가 작동합니다.',
          '화면 오른쪽 미니맵과 현재 위치 표시가 함께합니다.',
          '수정 동굴에서는 주 퀘스트 오브젝트 표시를 켜고 끌 수 있습니다.',
          '피해를 주고받는 전투 규칙은 DEV 공지대로 설계하고 있습니다.',
        ],
      },
      {
        index: '08', title: '다섯 레이드 보스', stage: 'current',
        body: '샤리트·가이아·루드라·흑기사·플루토의 전장에 들어갈 수 있습니다.',
        items: [
          '전장마다 원본 소개 영상을 미리 보고 들어갑니다.',
          '보스는 원본 배치와 크기로 서 있고, 전투 규칙을 정하기 전까지 공격하지 않습니다.',
        ],
      },
      {
        index: '09', title: '정령과 함께하는 영지', stage: 'current',
        body: '동행 정령과 영지에 방문한 정령이 돌아다니고, 걷기·달리기·점프로 영지를 둘러봅니다.',
        items: [
          '정령에게 다가가 대화하기를 고르면 원본 대화 연출이 이어지고, 선택지와 키워드로 답합니다.',
          '방문 정령을 불러내면 따라오고, 함께 마차에 오르면 나들이 장소를 고릅니다. 나들이는 하루 3번입니다.',
          '대화와 나들이 결과는 40단계 호감도와 하루 기록으로 게임 데이터베이스에 저장됩니다.',
          '영지 시간(낮·밤)과 날씨(맑음·눈·비)를 고를 수 있고, 가까이 가면 영지의 소리가 방향감 있게 들립니다.',
        ],
      },
      {
        index: '10', title: '환경설정', stage: 'current',
        body: '게임·전투·그래픽·사운드·언어·단축키를 나눠 설정합니다.',
        items: [
          '그래픽: 화면 모드(전용 전체화면·테두리 없음·창 모드), 화면 해상도, 프레임 제한(0은 디스플레이 최대), FPS 표시, 수직 동기화, 렌더 해상도 배율, 그림자, 후처리, 블룸, FXAA, MSAA(최대 8배), 텍스처 이방성 필터링(최대 16배), 파티클 품질.',
          '사운드: 전체 음량·배경 음악·정령 보이스·효과음·환경음·인터페이스 음량과 백그라운드 음소거.',
          '게임: 카메라 감도·Y축 반전·자유 카메라 룩앳·소환 연출 오퍼레이터·영지 시간과 날씨·개발 모드. 전투: 자동 타게팅·전투 HUD 표시·동행 정령 목록 표시.',
          '단축키: 이동·달리기·점프·상호작용·기본 공격·스킬·파티·메뉴·자유 카메라 키를 모두 바꿀 수 있습니다.',
        ],
      },
      {
        index: '11', title: '런처와 설치', stage: 'current',
        body: '런처가 실행 환경을 확인하고 게임 데이터를 설치한 뒤 게임을 시작합니다.',
        items: [
          '운영체제와 그래픽카드, 렌더 방식을 확인해 결과를 짧게 보여 줍니다.',
          '렌더 방식은 자동 선택 또는 Direct3D 12·Direct3D 11·CPU(three.js) 중에서 고릅니다.',
          '공개 저장소에서 같은 게임 버전의 카탈로그를 확인하고, 맵 팩 19개와 일반 데이터 팩 12개 가운데 필요한 팩만 내려받습니다.',
          '패치노트 버튼은 이 페이지를 열고, 실행 기록에는 운영체제·Windows 빌드·CPU·메모리·그래픽카드 정보가 남아 문제 제보에 쓰입니다.',
        ],
      },
    ],
    updateEyebrow: '메피스토펠레스의 준비 기록',
    updateTitle: 'V0.0.2에서 달라진 이야기',
    updateSubtitle: '테스터 제보 수정부터 개발 방향 공지의 구현까지',
    updateDescription: 'V0.0.2는 일반 사용자에게 알린 개발 방향 공지 13가지가 진행되는 버전입니다. 첫 공개본의 테스터 제보에 따른 수정과 함께, 공지 항목마다 지금 게임 코드에 구현된 변화를 적었습니다.',
    updatePatchTitle: 'V0.0.2 변경 사항',
    updatePatchCaution: '아래 항목은 현재 V0.0.2 게임 코드에 구현된 내용입니다. 실제로 내려받을 수 있는 버전은 다운로드 구역에 따로 표시합니다.',
    updatePatchItems: [
      { id: '공지 01', title: '구버전 Windows 지원', body: '런처와 게임이 Windows 10 1709(빌드 16299)부터 Windows 11까지 운영체제 빌드를 판정해 지원 범위를 알려 주고, 쓸 수 있는 렌더 방식으로 실행합니다.' },
      { id: '공지 03', title: 'CPU·GPU 렌더 선택', body: 'V0.0.1의 NVIDIA·Direct3D 12 전용 실행에서 Direct3D 11과 CPU(three.js) 렌더, 기기에 맞는 자동 선택을 더했습니다.' },
      { id: '공지 04', title: '게임 데이터 저장', body: '보유 재화·정령·파티와 영지의 정령·호감도·대화·나들이 기록을 sqlite3 게임 데이터베이스에 저장합니다.' },
      { id: '공지 05', title: '작은 게임 패키지', body: '게임 데이터를 맵 팩 19개(.evtm)와 일반 데이터 팩 12개(.evtp)로 나눠, 런처가 필요한 팩만 받아 설치합니다.' },
      { id: '공지 06', title: '정령 소환 연출', body: '메피스토펠레스·벨레스·릴리스의 원본 소환 연출을 연결했고, 환경설정에서 연출 오퍼레이터를 고르며 건너뛰기 버튼이나 ESC로 넘길 수 있습니다.' },
      { id: '공지 07', title: '맵과 정령의 원본 표현', body: '누락됐던 맵 재질·텍스처·셰이더와 정령의 눈·얼굴·몸·외곽선 셰이더를 원본 값으로 재현했습니다.' },
      { id: '공지 08', title: '얼티밋·메인 스킬', body: '정령의 얼티밋과 메인 스킬 연출을 원본과 같게 교정했습니다.' },
      { id: '공지 09', title: '스킬 중 이동', body: '기본 공격과 스킬을 쓰는 동안에도 움직일 수 있고(기본 공격 중 0.9배, 스킬 중 0.3배), 하체와 상체 동작을 나눠 자연스럽게 잇습니다.' },
      { id: '공지 11', title: '영지의 정령과 나들이', body: '영지에서 정령이 돌아다니고, 대화·불러내기·나들이를 할 수 있습니다. 결과는 호감도와 하루 기록에 저장됩니다.' },
      { id: '공지 12', title: '영지의 시간·날씨·소리', body: '가까이 가면 방향감 있게 들리는 영지 소리와 함께, 낮·밤 시간과 맑음·눈·비 날씨를 고를 수 있습니다.' },
      { id: 'V0.0.2', title: '감상과 환경설정', body: '자유 카메라 룩앳 ON/OFF와 바닥 클릭 이동, 정령 도감의 크게 보기, 화면 모드(전용 전체화면·테두리 없음·창 모드)와 해상도 선택, FPS 표시 옵션을 더했습니다.' },
      { id: 'V0.0.2', title: '런처', body: '실행 환경(운영체제·그래픽카드·렌더 방식) 확인 표시, 이 페이지로 가는 패치노트 버튼, 문제 제보에 쓰는 상세 실행 기록(운영체제·Windows 빌드·CPU·메모리·그래픽카드)을 더했습니다.' },
    ],
    updateJump: '개발 일정 살펴보기',
    roadmapEyebrow: '개발 일정',
    roadmapTitle: '다음은 V0.0.3입니다',
    roadmapSubtitle: '영지의 나들이 다음, 에덴의 더 넓은 이야기로',
    roadmapDescription: '현재 V0.0.2 코드에는 개발 방향 공지 13가지 가운데 대부분이 구현돼 있습니다. 그다음 V0.0.3에서는 본격적인 전투와 육성, 세계를 설계해 갑니다. 아래 상태는 실제 코드 구현을 기준으로 적었습니다.',
    roadmapCountUnit: '건',
    roadmapIssuesSummary: '첫 공개본 테스터 제보 기록 보기',
    roadmapNoticeTitle: '개발 방향 공지 13가지 · V0.0.2 구현 상태',
    roadmapNoticeDescription: '공지한 13가지 항목의 실제 구현 상태입니다. 상태는 코드 구현과 기기 확인에 따라 갱신합니다.',
    roadmapJump: '패치노트 다시 보기',
    roadmapReport: '새로운 문제 제보하기',
    issueFeedTitle: '지금 올라온 제보',
    issueFeedDescription: '현재 게임에서 새로운 문제를 발견하시면 GitHub에 남겨주세요. 아래에서 공개된 제보를 확인할 수 있습니다.',
    issueFeedEmpty: '이 목록에 표시할 이슈가 없습니다.',
    issueFeedFilterLabel: '이슈 목록 선택',
    issueFeedAll: '전체',
    issueFeedOpen: '진행 중',
    issueFeedClosed: '종료',
    issueFeedNumberLabel: '번호',
    issueFeedSubjectLabel: '제목',
    issueFeedStatusLabel: '상태',
    issueFeedDateLabel: '최근 수정',
    issueFeedPagesLabel: '이슈 목록 페이지',
    issueFeedPrevious: '이전',
    issueFeedNext: '다음',
    roadmapStages: [
      { id: 'current', title: 'V0.0.2 현재 코드', description: '테스터 제보 수정, CPU·GPU 렌더 선택, sqlite3 게임 데이터 저장, 맵·데이터 팩 분리, 원본 소환 연출, 얼티밋·메인 스킬 교정, 스킬 중 이동, 영지의 정령 생활·나들이·시간·날씨까지 구현돼 있습니다.', status: '현재 단계' },
      { id: 'platform', title: '실행 환경 확장', description: 'Windows 10 1709부터 Windows 11까지의 지원, CPU·GPU 렌더 선택, 작은 게임 패키지는 구현을 마쳤습니다. Linux x86-64는 이식을 진행하고 있습니다(진행률 {linuxProgress}).', status: 'Windows 완료 · Linux 진행 중' },
      { id: 'combat', title: '정령 표현과 기술 연출', description: '원본 표현, 소환 연출, 얼티밋·메인 스킬 교정, 스킬 중 이동을 마쳤고, 정령 추가 모션을 이어 가고 있습니다.', status: '대부분 완료 · 추가 모션 진행 중' },
      { id: 'world', title: 'V0.0.3과 이후', description: '본격적인 전투 메커니즘과 정령 육성 방향을 설계하고, 영지 건물 설치와 던전·스토리를 모을 오리진 메뉴, 월드 에디터로 이어 갑니다.', status: '설계 준비 중' },
    ],
    roadmapNotice: [
      { index: '01', title: '구버전 Windows 지원', body: '런처와 게임이 Windows 10 1709(빌드 16299)부터 Windows 11까지 운영체제 빌드를 판정해 지원 범위를 알려 주고, 쓸 수 있는 렌더 방식으로 실행합니다.', status: '구현 완료' },
      { index: '02', title: '리눅스 지원', body: 'Linux x86-64 런처·게임 이식을 진행하고 있습니다. 출시 레인 {linuxTotal}개 항목 중 {linuxDone}개(플랫폼 계층과 CEF UI 호스트 구성 요소)를 작성했고, UI 호스트 본체·진입점·빌드 대상·GitHub Actions 출시 레인이 남았습니다.', status: '진행 중 · {linuxProgress}' },
      { index: '03', title: '기기에 맞는 렌더', body: '자동 선택은 그래픽카드를 찾아 Direct3D 12, 안 되면 Direct3D 11을 쓰고, 그래픽카드가 없거나 두 방식이 모두 안 되면 CPU(three.js) 렌더로 같은 장면을 보여 줍니다. 런처에서 직접 고를 수도 있습니다.', status: '구현 완료' },
      { index: '04', title: '게임 데이터 저장', body: '보유 재화·정령·파티와 영지의 정령·호감도·대화·나들이 기록을 sqlite3 게임 데이터베이스에 저장합니다.', status: '구현 완료' },
      { index: '05', title: '작은 게임 패키지', body: '맵 19개는 맵마다 .evtm 팩, 일반 데이터는 12개 .evtp 팩으로 나눠, 런처가 필요한 팩만 받아 설치합니다.', status: '구현 완료' },
      { index: '06', title: '정령 소환 연출', body: '메피스토펠레스·벨레스·릴리스의 원본 소환 연출을 연결했고, 환경설정에서 연출 오퍼레이터를 고릅니다.', status: '구현 완료' },
      { index: '07', title: '맵과 정령의 원본 표현', body: '누락됐던 맵 재질·텍스처·셰이더와 정령의 눈·얼굴·몸·외곽선 셰이더를 원본 값으로 재현했습니다.', status: '구현 완료' },
      { index: '08', title: '얼티밋·메인 스킬', body: '정령의 얼티밋과 메인 스킬 연출을 원본과 같게 교정했습니다.', status: '구현 완료' },
      { index: '09', title: '스킬 중 이동', body: '기본 공격과 스킬을 쓰는 동안에도 움직일 수 있고(기본 공격 중 0.9배, 스킬 중 0.3배), 하체와 상체 동작을 나눠 자연스럽게 잇습니다.', status: '구현 완료' },
      { index: '10', title: '정령 추가 모션', body: '날아다니는 정령 19명과 탈것을 타는 정령의 이동 모션, 걷기 보정처럼 공개된 모델과 리깅으로 필요한 움직임을 더하고 있습니다.', status: '진행 중' },
      { index: '11', title: '영지의 정령과 나들이', body: '영지에서 정령이 돌아다니고 대화·불러내기·나들이를 하는 원본 동작을 재현했습니다. 영지 건물을 3D로 편집해 설치하는 기능은 아직 시작하지 않았습니다.', status: '정령 생활 완료 · 건물 착수 전' },
      { index: '12', title: '영지의 시간·날씨·소리', body: '가까이 가면 방향감 있게 들리는 영지 소리와 낮·밤 시간, 맑음·눈·비 날씨 설정이 구현돼 있습니다.', status: '구현 완료' },
      { index: '13', title: '오리진과 월드 에디터', body: '던전 원본 맵·메인 스토리·인연 스토리를 모을 오리진 메뉴와, 영지 에디터를 월드 에디터로 넓히는 작업은 아직 시작하지 않았습니다.', status: '착수 전' },
    ],
    updateEntries: [
      { id: 'T-A1', title: '일부 기기에서 게임이 바로 종료돼요', status: '수정 코드 반영', stage: 'updated', body: 'AMD 그래픽카드에서는 NVIDIA 전용 연산을 시작하지 않고 Direct3D 연산을 선택하도록 연결했습니다. 같은 증상이 남으면 실행 로그와 함께 알려주세요.', patchNote: 'AMD 그래픽카드에서 NVIDIA 전용 계산을 시도하지 않도록 경로를 분리했습니다.' },
      { id: 'T-B1', title: '게임을 열 수 없는 기기가 있어요', status: '수정 코드 반영', stage: 'updated', body: '기기에서 사용할 수 있는 화면 방식을 순서대로 선택하도록 연결했습니다. 새 버전에서도 실행할 수 없다면 기기 정보와 로그를 보내주세요.', patchNote: '기기에 맞는 화면 방식을 차례로 선택하는 경로를 연결했습니다.' },
      { id: 'T-C1', title: '화면 크기가 모니터와 맞지 않아요', status: '수정 코드 반영', stage: 'updated', body: '현재 모니터 크기를 기본 화면 크기로 읽고, 선택 가능한 크기를 설정에 표시하도록 연결했습니다. 다른 화면 크기에서도 어긋나면 알려주세요.', patchNote: '현재 모니터 크기를 기본값으로 쓰고, 선택 가능한 화면 크기를 설정에 연결했습니다.' },
      { id: 'T-C2', title: '장소가 바뀌어도 로비 음악이 들려요', status: '수정 코드 반영', stage: 'updated', body: '로비를 떠날 때 로비 음악을 멈추고 새 장소의 음악을 따로 재생하도록 연결했습니다. 음악이 겹치거나 끊기면 이동한 장소를 알려주세요.', patchNote: '로비 음악을 멈추는 시점과 장소별 음악 재생을 분리했습니다.' },
      { id: 'T-C3', title: '공격할 때 시선과 움직임이 어색해요', status: '추가 사례 요청', stage: 'feedback', body: '조준 방향과 머리 움직임을 잇는 코드는 있습니다. 새 버전에서 어색한 동작이 다시 보이면 정령·기술·화면을 함께 알려주세요.' },
      { id: 'T-C4', title: '적과의 전투', status: '개발 중', stage: 'developing', body: '정령의 공격 동작과 몬스터의 체력·피격 동작은 있지만, 현재 던전 몬스터는 공격 피해를 받도록 등록되지 않았습니다. 전투 완성 소식은 실제로 싸울 수 있게 연결한 뒤 전하겠습니다.' },
      { id: 'T-C5', title: '영지 계단에서 아래로 빠져요', status: '추가 사례 요청', stage: 'feedback', body: '걷는 지면과 단차를 확인하는 코드가 있습니다. 새 버전에서 같은 계단에서 발이 빠진다면 위치와 화면을 알려주세요.' },
    ],
    guideEyebrow: '시작 안내',
    guideTitle: '처음 오셨군요, 구원자님',
    guideSubtitle: '첫 실행은 네 단계로 안내해 드릴게요',
    guideDescription: '지금 내려받을 수 있는 것은 첫 공개본 V0.0.1입니다. 설치 순서는 네 단계예요. 제가 곁에서 안내해 드리겠습니다.',
    guideSteps: [
      { index: '01', title: '파일을 받아 압축을 풀어 주세요', body: '아래 다운로드에서 V0.0.1 압축 파일을 받으신 뒤, 원하는 위치에 풀어 주세요.' },
      { index: '02', title: '런처를 열어 주세요', body: '압축을 푼 폴더에서 ev_launcher.exe를 실행해 주세요.' },
      { index: '03', title: '설치를 눌러 주세요', body: '처음에는 게임 자료를 받아야 합니다. 빨간 설치 버튼을 누르면 진행 상황을 확인하실 수 있어요.' },
      { index: '04', title: '게임 시작을 눌러 주세요', body: '설치가 끝나면 게임 시작을 눌러 주세요. 이제 정령들이 구원자님을 기다리고 있습니다.' },
    ],
    mephistoSceneTitle: '제가 곁에서 안내해 드릴게요',
    mephistoPanelTitle: '말을 골라 주세요',
    mephistoLoading: '메피스토펠레스를 부르고 있습니다…',
    mephistoUnavailable: '3D 모습을 불러오지 못했습니다. 아래의 음성과 안내는 계속 이용하실 수 있습니다.',
    mephistoVoiceUnavailable: '음성을 재생하지 못했습니다. 대사는 아래에서 읽으실 수 있습니다.',
    mephistoVoiceNote: '원본 한국어 음성 · 대사는 선택한 언어로 표시됩니다.',
    mephistoOpen: '메피스토펠레스 안내 열기',
    mephistoClose: '메피스토펠레스 안내 접기',
    mephistoDragHint: '메피스토펠레스 위치 이동. 드래그하거나 방향키로 옮기고, 짧게 누르면 반응합니다.',
    mephistoMessages: {
      top: '구원자님, 어서 오세요. 제가 곁에서 안내해 드릴게요.',
      features: '먼저 정령들과 만날 수 있는 곳부터 둘러보실까요?',
      updates: '현재 V0.0.2 코드에서 바뀐 점을 안내해 드릴게요.',
      roadmap: '영지 나들이 다음에는 V0.0.3의 이야기가 이어집니다.',
      guide: '처음 오셨군요. 네 단계를 따라오시면 됩니다.',
      download: '현재 내려받을 수 있는 것은 첫 공개본 V0.0.1이에요.',
      specs: '실행 전에 필요한 사양도 확인해 주세요.',
      lounge: '열정페이로 같이 만들고 싶은 바이브코더, 모델러, 어떤 기여자든 환영합니다.',
      end: '구원자님, 다음 이야기에서도 기다리고 있겠습니다.',
    },
    mephistoReactions: {
      greeting: { label: '인사 듣기', caption: '구원자님, 어서 오세요.' },
      touch: { label: '고양이 이야기', caption: '아케나인의 삼색 고양이들과 얼룩 고양이들은 사이가 나빠요. 이유가 뭘까요. 주목할 만한 현상입니다.' },
      touchsp: { label: '놀란 반응', caption: '아…' },
      touchsp02: { label: '다정한 반응', caption: '구원자님, 안아드려도 될까요? 그러고 싶어요.' },
    },
    downloadEyebrow: '내려받기',
    downloadTitle: '첫 공개본을 내려받으세요',
    downloadSubtitle: '공개 다운로드 V0.0.1 · 현재 코드 V0.0.2(Windows 출시 준비 중) · 다음 V0.0.3',
    downloadDescription: 'V0.0.1은 Windows에서만 실행됩니다. Linux x86-64 버전은 이식을 진행하고 있어요. macOS에서는 아직 만나 뵐 수 없어요.',
    platformLabel: {
      windows: 'Windows',
      linux: 'Linux',
      macos: 'macOS',
    },
    platformStatus: {
      available: '내려받기 가능',
      preparing: '준비 중',
      unsupported: '지원하지 않음',
    },
    platformProgress: '진행률 {linuxProgress} · {linuxDone}/{linuxTotal}개 항목',
    downloadCurrent: '내려받을 수 있는 버전',
    downloadPlatformLabel: '플랫폼',
    downloadHashLabel: 'SHA-256',
    downloadPatchLabel: '패치 구성',
    downloadLatest: '내려받기',
    downloadPatchFiles: '패치 파일 {count}개 · {size}',
    downloadNoRelease: '아직 게시된 릴리스가 없습니다. 준비가 끝나는 대로 이 페이지에 올라갑니다.',
    downloadNotesLabel: '패치 노트',
    downloadSizeLabel: '배포본 크기',
    downloadArchiveLabel: '배포 파일',
    downloadRedirectNote: '내려받기를 누르면 GitHub에서 압축 파일을 받습니다. 압축을 풀고 런처를 실행해 주세요. 처음에는 게임 자료를 추가로 받으니, 설치가 끝날 때까지 기다려 주시면 됩니다.',
    downloadPrevious: '이전 릴리스',
    utilityTitle: '실행에 필요한 준비물',
    utilityDescription: '게임을 여는 데 필요한 준비물입니다. 없는 항목만 공식 안내에서 받아 주세요.',
    utilityRequired: '필수',
    utility: [
      { id: 'directx', label: 'DirectX 12', note: 'Windows 10·11에 포함되어 있어 따로 설치하는 파일이 없습니다. Windows 업데이트를 최신으로 유지해 주십시오.' },
      { id: 'nvidia', label: 'NVIDIA 그래픽 드라이버', note: 'NVIDIA 그래픽카드(GeForce GTX 16·RTX 20 시리즈 이상)와 최신 드라이버가 필요합니다.' },
      { id: 'webview2', label: 'Microsoft Edge WebView2 런타임', note: '게임 화면과 메뉴를 표시하는 데 필요합니다. Windows 11에는 기본으로 들어 있습니다.' },
      { id: 'vcredist', label: 'Visual C++ 재배포 패키지 (x64)', note: '배포 파일에 함께 들어 있어 보통은 설치하지 않아도 됩니다.' },
    ],
    specEyebrow: '필요 사양',
    specTitle: '실행 전에 확인해 주십시오',
    specRecommendedTitle: '권장 사양',
    specRecommendedBody: '권장 사양은 아직 실제 기기에서 측정해 확정하지 않았습니다. 성능 목표는 평균 사양 GTX 1060에서 144FPS이며, 제보 기기에서의 결과를 계속 확인하고 있습니다.',
    specVersions: [
      {
        title: 'V0.0.1 공개본 · 지금 내려받기',
        rows: [
          { label: '운영체제', value: 'Windows 10·11 (64비트). V0.0.1은 Linux·macOS를 지원하지 않음' },
          { label: '그래픽', value: 'DirectX 12(셰이더 모델 6.6) 지원 NVIDIA GeForce GTX 16·RTX 20 시리즈 이상' },
          { label: '드라이버', value: '최신 NVIDIA 그래픽 드라이버' },
          { label: '저장 공간', value: '약 4.3 GB (게임 데이터 약 4.2 GB 포함)' },
          { label: '인터넷', value: '처음 설치할 때 게임 데이터를 내려받는 데 필요' },
          { label: '실행', value: '런처(ev_launcher.exe)로 실행, 항상 전체화면' },
          { label: '버전', value: 'V0.0.1 알파 테스트' },
        ],
      },
      {
        title: 'V0.0.2 현재 코드 · Windows 출시 준비 중',
        rows: [
          { label: '운영체제', value: 'Windows 10 1709(빌드 16299)부터 Windows 11까지 (64비트). Linux x86-64는 이식 진행 중({linuxProgress}), macOS는 지원하지 않음' },
          { label: '그래픽', value: 'Direct3D 12(기능 수준 11_0 이상) 또는 Direct3D 11(기능 수준 10_0 이상)을 쓸 수 있는 그래픽카드. 둘 다 쓸 수 없거나 그래픽카드가 없으면 CPU(three.js) 렌더로 실행' },
          { label: '드라이버', value: '그래픽카드 제조사의 최신 드라이버' },
          { label: '화면 구성 요소', value: 'Microsoft Edge WebView2 런타임 (Windows 11에는 기본 포함)' },
          { label: '저장 공간', value: '약 4.5 GB (게임 데이터 팩 31개 약 4.4 GB 포함)' },
          { label: '인터넷', value: '처음 설치할 때 공개 저장소에서 게임 데이터 팩을 내려받는 데 필요' },
          { label: '실행', value: '런처(ev_launcher.exe)로 실행. 화면 모드는 전용 전체화면·테두리 없음·창 모드 중에서 고르고, 해상도와 FPS 표시도 설정' },
          { label: '버전', value: 'V0.0.2 알파 테스트 (Windows 출시 준비 중)' },
        ],
      },
    ],
    loungeEyebrow: '개발자 구인 라운지',
    loungeTitle: '함께 만드는 Another',
    loungeReason: '정령 한 명이 에덴에서 움직이기까지 모델, 모션, 사운드, UI와 엔진이 모두 이어져야 합니다. V0.0.2에서 영지 나들이까지 연결했고, V0.0.3에서는 전투와 다음 여정을 더 완성해야 합니다. 각자의 작업을 끝까지 이어 줄 열정이 필요합니다.',
    loungeInvite: '열정페이로 같이 만들고 싶은 바이브코더, 모델러 등 어떤 기여자든 환영합니다.',
    loungeFlowLabel: 'evt 제작 흐름',
    loungeFlow: ['원본 번들', '에셋 변환·카탈로그', '엔진·게임 클라이언트', '런처·배포본'],
    loungeStackLabel: 'evt 개발 스택',
    positionSpecs: '사양',
    positionEnd: '© Another',
    loungeStack: ['C++26', 'SDL3', 'TypeScript', 'SolidJS', 'three.js', 'Direct3D 12', 'Direct3D 11', 'xmake'],
    footerLine: '구원자와 정령이 함께 걷는, 끝나지 않는 이야기.',
    footerNavLabel: '안내 바로가기',
    footerReport: '이슈 신고',
    footerBack: '맨 위로',
    footerBackArrow: '↑',
    footerCopyright: '© 2026 ANOTHER',
  },
  en: {
    brandName: 'Another',
    brandFirst: 'Ano',
    brandSecond: 'ther',
    metaDescription: 'EVT: Another is a party dungeon game with the Savior and the Souls. See the content that works today, the implementation status of the 13 V0.0.2 development notices, the upcoming V0.0.3 roadmap, and the available V0.0.1 download.',
    navLabel: 'Main menu',
    navGame: 'Game',
    navUpdates: 'Patch notes',
    navRoadmap: 'Roadmap',
    navGuide: 'Getting started',
    navDownload: 'Download',
    navLanguage: 'Choose language',
    navMenuOpen: 'Open menu',
    navMenuClose: 'Close menu',
    musicTitle: 'Melody of Eden',
    musicTrack: 'Lobby melody · 02',
    musicPlay: 'Play background music',
    musicPause: 'Pause background music',
    musicMute: 'Mute background music',
    musicUnmute: 'Unmute background music',
    musicSeek: 'Background music position',
    musicUnavailable: 'Background music is unavailable',
    localeKo: 'KO',
    localeEn: 'EN',
    skipToContent: 'Skip to content',
    heroEyebrow: 'A NOTE FROM OPERATOR MEPHISTOPHELES',
    heroTagline: 'Vital sign check completed. Welcome, Savior.',
    heroDescription: 'I am Mephistopheles. I will help you and the Souls find your way through Eden. I have kept the story of our first release and what we are preparing here for you. Please take your time. A slice of cake would be nice, too.',
    heroPrimary: 'Download',
    heroSecondary: 'About the game',
    heroScroll: 'Review below',
    heroDevNotice: 'Full combat mechanics, Soul growth and the overall game content are still being designed. Right now our first priority is reproducing the original game’s features as they are.',
    heroDevLink: 'Read the DEV notice',
    featureEyebrow: 'THE GAME',
    featureTitle: 'Begin your adventure with the Souls',
    featureSubtitle: 'From the lobby, town and dungeons to summons and viewing: everything that works today',
    featureDescription: 'Another is a party dungeon game where you team up with the Souls to explore Eden. Below is every piece of content that works in the current V0.0.2 game code, feature by feature. The public V0.0.1 download offers the lobby and the practice arena.',
    featureStage: {
      release: 'Since V0.0.1',
      current: 'V0.0.2',
    },
    devNoticeLabel: 'DEV NOTICE',
    devNoticeTitle: 'Right now we reproduce the original features first',
    devNoticeBody: 'Full combat mechanics, the direction of Soul growth and the overall game content are still being designed. Our first priority is “feature reproduction”: bringing the original game’s visuals, movement, direction and sound to this engine as they are.',
    devNoticeItems: [
      'Combat: Soul attack and skill motions and monster health and hit reactions exist, but the rules for dealing and taking damage are still being designed. Raid bosses stand at their original positions and sizes and do not attack.',
      'Growth: How Souls grow has not been decided yet. This test build turns developer mode on by default, so every Soul is unlocked and summons and purchases are unlimited; you can turn it off in Settings.',
      'Rewards: Dungeon coins and raid special tickets are only shown as guidance for now; real rewards will be connected as combat is designed.',
      'Content: The Origin menu for the main story, bond stories and original dungeon maps, town buildings, and the world editor will be designed next.',
    ],
    feature: [
      {
        index: '01', title: 'The lobby, a haven for the Savior', stage: 'release',
        body: 'Place Souls in the lobby and view them up close. Show the whole party or just one Soul chosen from the collection.',
        items: [
          'Click to touch a Soul and see her react; Souls with Special Touch lines react differently to Special Touch.',
          'Free Movement lets you walk around the lobby yourself, and Appreciation Mode brings you back at any time.',
          'Free Camera lets you move, rise, descend and drag to frame the shot. With Look-at on, the Soul looks at the camera, and clicking the floor makes her walk there.',
          'Photo Mode and Hide Interface leave only the scene on screen.',
          'The BGM player lets you pick Basic, Story, Soul and Event tracks and build playlists. Liked tracks keep playing across maps and menus.',
        ],
      },
      {
        index: '02', title: 'Collection and Full View', stage: 'current',
        body: 'Search your Souls by name and filter them by All, Owned and Party.',
        items: [
          'Each Soul has Profile, Introduction, Costumes, Skills and Stats.',
          'Full View offers the same screen and controls as Free Camera, including Look-at and click-to-move.',
          'Turn weapon and mask parts on or off, and choose Original or Walk locomotion. Souls that ride a mount can also turn the mount on or off.',
          'Add Souls to the party or remove them, and show them in the lobby right away.',
        ],
      },
      {
        index: '03', title: 'Soul summons and the original summon direction', stage: 'current',
        body: 'Summon Souls with tickets to fill your collection and bring them into your party.',
        items: [
          'Soul Summon gives every Soul an equal chance; Special Summon picks from Souls you have not collected yet, or from all Souls once your collection is complete.',
          'Summon ×1 and ×10, summon rates, results split into new and duplicate Souls, and Summon Again are supported.',
          'The original summon direction plays. Choose the operator from Mephistopheles, Beleth and Lilith in Settings, and skip it with the Skip button or ESC.',
        ],
      },
      {
        index: '04', title: 'Shop and wallet', stage: 'current',
        body: 'The Ticket Exchange trades coins for summon tickets.',
        items: [
          'A summon ticket costs 1,000 coins and a bundle of 10 costs 10,000 coins; you can buy up to 99 at a time.',
          'Special tickets are not sold in the shop and are being prepared as raid rewards.',
          'Coins, summon tickets and special tickets are saved in the game database.',
        ],
      },
      {
        index: '05', title: 'A party of the Savior and the Souls', stage: 'current',
        body: 'Form a party of up to 4 with the Savior and Souls; at least one member must remain.',
        items: [
          'The Savior can join the party too. The Savior fights with basic attacks; switch to a Soul to use skills.',
          'Switch the controlled member with the Party window or slot keys 1 to 4.',
          'Check your current party from the lobby and the dungeon list and jump to party formation.',
        ],
      },
      {
        index: '06', title: 'Training Grounds', stage: 'release',
        body: 'Try a Soul’s basic attack and skills 1 to 4 and check their motion and direction.',
        items: [
          'You can keep moving while using basic attacks and skills: at 0.9× speed during basic attacks and 0.3× during skills.',
          'Movement, run, jump, attack and skill keys can be rebound in Settings.',
        ],
      },
      {
        index: '07', title: 'Explore six dungeons', stage: 'current',
        body: 'Enter Arkenine Palace, Crystal Cave, Forgotten Ruins, Cave of Death, Temple of Artifacts and The Origin of the End.',
        items: [
          'Monsters stand at their original positions, and doors, bridges and teleports (with a move prompt and confirmation) work.',
          'A minimap and your current location are shown on the right.',
          'In Crystal Cave you can show or hide the main quest objects.',
          'Rules for dealing and taking damage are being designed, as the DEV notice explains.',
        ],
      },
      {
        index: '08', title: 'Five raid bosses', stage: 'current',
        body: 'Enter the battlefields of Charite, Gaia, Ruthra, Dark Knight and Pluto.',
        items: [
          'Preview each battlefield with its original introduction movie before entering.',
          'Bosses stand with their original placement and size and do not attack until the combat rules are decided.',
        ],
      },
      {
        index: '09', title: 'Town life with the Souls', stage: 'current',
        body: 'Party Souls and visiting Souls wander the town, and you can walk, run and jump around it.',
        items: [
          'Approach a Soul and choose Talk to play the original conversation scene and answer with choices and keywords.',
          'Call a visiting Soul to follow you, board the carriage together and choose an outing destination. You can go on 3 outings a day.',
          'Conversation and outing results are saved in the game database as 40-level affinity and the daily record.',
          'Choose the town time (day or night) and weather (sunny, snowy or rainy), and hear town sounds with a sense of direction as you approach.',
        ],
      },
      {
        index: '10', title: 'Settings', stage: 'current',
        body: 'Settings are grouped into Game, Combat, Graphics, Sound, Language and Key bindings.',
        items: [
          'Graphics: window mode (exclusive fullscreen, borderless or windowed), display resolution, frame limit (0 for the display maximum), Show FPS, vertical sync, render resolution scale, shadows, post-processing, bloom, FXAA, MSAA (up to 8×), anisotropic texture filtering (up to 16×) and particle quality.',
          'Sound: master, music, voice, sound effects, ambience and interface volume, plus mute in background.',
          'Game: camera sensitivity, invert camera Y, free camera Look-at, summon director operator, town time and weather, and developer mode. Combat: auto targeting, show combat HUD and show party list.',
          'Key bindings: every key for movement, run, jump, interact, basic attack, skills, party, menus and the free camera can be rebound.',
        ],
      },
      {
        index: '11', title: 'Launcher and installation', stage: 'current',
        body: 'The launcher checks your environment, installs the game data and starts the game.',
        items: [
          'It checks your operating system, graphics card and render method and shows a short result.',
          'Choose automatic selection or Direct3D 12, Direct3D 11 or CPU (three.js) rendering.',
          'It verifies the catalog for the same game version in the public repository and downloads only the packs you need from 19 map packs and 12 data packs.',
          'The Patch notes button opens this page, and the launch log records your operating system, Windows build, CPU, memory and graphics card for problem reports.',
        ],
      },
    ],
    updateEyebrow: 'A RECORD FOR YOU, SAVIOR',
    updateTitle: 'What changed in V0.0.2',
    updateSubtitle: 'From tester fixes to the development notices',
    updateDescription: 'V0.0.2 is the version in which the 13 development notices shared with players are put into practice. Alongside the fixes from first-release tester reports, each notice item lists what is implemented in the game code today.',
    updatePatchTitle: 'V0.0.2 changes',
    updatePatchCaution: 'These items are implemented in the current V0.0.2 game code. The version you can actually download is shown separately in the download section.',
    updatePatchItems: [
      { id: 'Notice 01', title: 'Older Windows support', body: 'The launcher and game identify the operating system build from Windows 10 1709 (build 16299) through Windows 11, show the supported range and run with an available render method.' },
      { id: 'Notice 03', title: 'CPU and GPU rendering', body: 'Beyond the NVIDIA and Direct3D 12 only V0.0.1, Direct3D 11 and CPU (three.js) rendering were added with automatic selection for each device.' },
      { id: 'Notice 04', title: 'Game data storage', body: 'Your wallet, Souls and party, and town Souls, affinity, conversations and outings are saved in the sqlite3 game database.' },
      { id: 'Notice 05', title: 'Smaller game packages', body: 'Game data is split into 19 map packs (.evtm) and 12 data packs (.evtp), and the launcher installs only the packs you need.' },
      { id: 'Notice 06', title: 'Soul summoning scenes', body: 'The original summon direction of Mephistopheles, Beleth and Lilith is connected; choose the operator in Settings and skip it with the Skip button or ESC.' },
      { id: 'Notice 07', title: 'Original world and Soul visuals', body: 'Missing map materials, textures and shaders and the Souls’ eye, face, body and outline shaders are reproduced with the original values.' },
      { id: 'Notice 08', title: 'Ultimate and main skills', body: 'Souls’ ultimate and main skill direction now matches the originals.' },
      { id: 'Notice 09', title: 'Move while using skills', body: 'You can move while using basic attacks and skills (0.9× during basic attacks, 0.3× during skills), with lower and upper body motion blended separately.' },
      { id: 'Notice 11', title: 'Town life and outings', body: 'Souls wander the town, and you can talk to them, call them and go on outings. Results are saved to affinity and the daily record.' },
      { id: 'Notice 12', title: 'Town time, weather and sound', body: 'Along with town sounds heard with a sense of direction up close, you can choose day or night and sunny, snowy or rainy weather.' },
      { id: 'V0.0.2', title: 'Viewing and settings', body: 'Added the free camera Look-at toggle and click-to-move, Full View in the collection, window mode (exclusive fullscreen, borderless or windowed) with resolution choice, and the Show FPS option.' },
      { id: 'V0.0.2', title: 'Launcher', body: 'Added the environment check (operating system, graphics card and render method), a Patch notes button that opens this page, and a detailed launch log for problem reports (operating system, Windows build, CPU, memory and graphics card).' },
    ],
    updateJump: 'Explore the roadmap',
    roadmapEyebrow: 'ROADMAP',
    roadmapTitle: 'Next comes V0.0.3',
    roadmapSubtitle: 'Beyond town outings, a wider Eden awaits',
    roadmapDescription: 'Most of the 13 development notices are already implemented in the current V0.0.2 code. Next, V0.0.3 designs full combat, growth and the wider world. The statuses below are based on the actual code.',
    roadmapCountUnit: ' reports',
    roadmapIssuesSummary: 'View reports from the first release',
    roadmapNoticeTitle: '13 development notices · V0.0.2 status',
    roadmapNoticeDescription: 'The actual implementation status of the 13 announced items. Statuses are updated as implementation and device checks progress.',
    roadmapJump: 'Return to patch notes',
    roadmapReport: 'Report a new problem',
    issueFeedTitle: 'Reports from the community',
    issueFeedDescription: 'Found a new problem in the game? Tell us on GitHub. Public reports appear below.',
    issueFeedEmpty: 'There are no issues in this list.',
    issueFeedFilterLabel: 'Choose issue list',
    issueFeedAll: 'All',
    issueFeedOpen: 'Open',
    issueFeedClosed: 'Closed',
    issueFeedNumberLabel: 'No.',
    issueFeedSubjectLabel: 'Title',
    issueFeedStatusLabel: 'Status',
    issueFeedDateLabel: 'Updated',
    issueFeedPagesLabel: 'Issue list pages',
    issueFeedPrevious: 'Previous',
    issueFeedNext: 'Next',
    roadmapStages: [
      { id: 'current', title: 'Current V0.0.2 code', description: 'Tester fixes, CPU and GPU render selection, sqlite3 game data storage, split map and data packs, original summon direction, ultimate and main skill correction, moving while using skills, and town life, outings, time and weather are implemented.', status: 'Current stage' },
      { id: 'platform', title: 'Broader device support', description: 'Support from Windows 10 1709 through Windows 11, CPU and GPU render selection and smaller game packages are complete. The Linux x86-64 port is in progress ({linuxProgress}).', status: 'Windows done · Linux in progress' },
      { id: 'combat', title: 'Soul visuals and skill direction', description: 'Original visuals, summon direction, ultimate and main skill correction and moving while using skills are complete; more Soul animations are in progress.', status: 'Mostly done · animations in progress' },
      { id: 'world', title: 'V0.0.3 and beyond', description: 'Design full combat mechanics and Soul growth, then continue with town buildings, the Origin menu for dungeons and stories, and the world editor.', status: 'Design in preparation' },
    ],
    roadmapNotice: [
      { index: '01', title: 'Older Windows support', body: 'The launcher and game identify the operating system build from Windows 10 1709 (build 16299) through Windows 11, show the supported range and run with an available render method.', status: 'Implemented' },
      { index: '02', title: 'Linux support', body: 'The Linux x86-64 launcher and game port is in progress. {linuxDone} of {linuxTotal} release-lane items (the platform layer and CEF UI host components) are written; the UI host core, entry points, build targets and the GitHub Actions release lane remain.', status: 'In progress · {linuxProgress}' },
      { index: '03', title: 'Rendering for each device', body: 'Automatic selection finds a graphics card and uses Direct3D 12, then Direct3D 11; with no graphics card or neither method available, CPU (three.js) rendering shows the same scene. You can also choose it in the launcher.', status: 'Implemented' },
      { index: '04', title: 'Game data storage', body: 'Your wallet, Souls and party, and town Souls, affinity, conversations and outings are saved in the sqlite3 game database.', status: 'Implemented' },
      { index: '05', title: 'Smaller game packages', body: 'Each of the 19 maps ships as its own .evtm pack and general data as 12 .evtp packs; the launcher installs only the packs you need.', status: 'Implemented' },
      { index: '06', title: 'Soul summoning scenes', body: 'The original summon direction of Mephistopheles, Beleth and Lilith is connected, and the operator is chosen in Settings.', status: 'Implemented' },
      { index: '07', title: 'Original world and Soul visuals', body: 'Missing map materials, textures and shaders and the Souls’ eye, face, body and outline shaders are reproduced with the original values.', status: 'Implemented' },
      { index: '08', title: 'Ultimate and main skills', body: 'Souls’ ultimate and main skill direction now matches the originals.', status: 'Implemented' },
      { index: '09', title: 'Move while using skills', body: 'You can move while using basic attacks and skills (0.9× during basic attacks, 0.3× during skills), with lower and upper body motion blended separately.', status: 'Implemented' },
      { index: '10', title: 'More Soul animations', body: 'Movement for the 19 flying Souls and the mounted Soul, walk correction and other motions are being added with the available models and rigs.', status: 'In progress' },
      { index: '11', title: 'Town life and outings', body: 'The original town behavior is reproduced: Souls wander, talk, can be called and go on outings. Editing and placing town buildings in 3D has not started yet.', status: 'Town life done · buildings not started' },
      { index: '12', title: 'Town time, weather and sound', body: 'Town sounds heard with a sense of direction up close, day and night time, and sunny, snowy and rainy weather are implemented.', status: 'Implemented' },
      { index: '13', title: 'Origin and world editor', body: 'The Origin menu for original dungeon maps, the main story and bond stories, and turning the town editor into a world editor, have not started yet.', status: 'Not started' },
    ],
    updateEntries: [
      { id: 'T-A1', title: 'The game closes at startup on some devices', status: 'Code fix added', stage: 'updated', body: 'AMD graphics cards now use Direct3D compute instead of starting NVIDIA-only compute. If the game still closes, please send the launch log.', patchNote: 'Separated the NVIDIA calculation path so AMD cards do not start it.' },
      { id: 'T-B1', title: 'Some devices cannot open the game', status: 'Code fix added', stage: 'updated', body: 'The game now selects an available display method in order. If the new build still does not start, please send your device details and log.', patchNote: 'Connected the path that tries available screen drawing methods in order.' },
      { id: 'T-C1', title: 'The screen size does not match the monitor', status: 'Code fix added', stage: 'updated', body: 'The game now reads the current monitor size by default and shows available sizes in settings. Tell us if another display size still looks wrong.', patchNote: 'Made the current monitor size the default and connected available sizes to settings.' },
      { id: 'T-C2', title: 'Lobby music continues in another place', status: 'Code fix added', stage: 'updated', body: 'Lobby music now stops when you leave, while the next place plays its own music. Tell us which places you visited if music overlaps or cuts out.', patchNote: 'Separated the moment lobby music stops from music played in each place.' },
      { id: 'T-C3', title: 'Looking and moving feel wrong during attacks', status: 'More examples welcome', stage: 'feedback', body: 'The code connects aim direction to head movement. If an animation still feels wrong in the new build, please show us the Soul, skill and screen.' },
      { id: 'T-C4', title: 'Combat against enemies', status: 'In development', stage: 'developing', body: 'Soul attack motions and monster health and hit reactions exist, but dungeon monsters are not currently registered to take attack damage. We will announce combat when you can actually fight them.' },
      { id: 'T-C5', title: 'You fall through the stairs in town', status: 'More examples welcome', stage: 'feedback', body: 'The code checks walkable ground and step height. If your footing still slips on the same stairs in the new build, please show us where and what happened.' },
    ],
    guideEyebrow: 'GETTING STARTED',
    guideTitle: 'Welcome, Savior',
    guideSubtitle: 'Four steps to start the first release',
    guideDescription: 'V0.0.1 is the first release available to download. There are four steps. I will guide you through them.',
    guideSteps: [
      { index: '01', title: 'Download and unzip the file', body: 'Use the download below to get the V0.0.1 archive, then unzip it wherever you would like.' },
      { index: '02', title: 'Open the launcher', body: 'Run ev_launcher.exe from the unzipped folder.' },
      { index: '03', title: 'Press Install', body: 'The first launch needs to download game data. Press the red Install button and watch its progress.' },
      { index: '04', title: 'Press Start Game', body: 'Once installation finishes, press Start Game. The Souls are waiting for you.' },
    ],
    mephistoSceneTitle: 'I will guide you from here',
    mephistoPanelTitle: 'Talk to me, Savior',
    mephistoLoading: 'Calling Mephistopheles…',
    mephistoUnavailable: 'The 3D model could not be loaded. The voice and guide below are still available.',
    mephistoVoiceUnavailable: 'The voice could not be played. You can read the line below.',
    mephistoVoiceNote: 'Original Korean voice · lines appear in your selected language.',
    mephistoOpen: 'Open Mephistopheles guide',
    mephistoClose: 'Collapse Mephistopheles guide',
    mephistoDragHint: 'Move Mephistopheles. Drag or use the arrow keys; press briefly for a reaction.',
    mephistoMessages: {
      top: 'Welcome, Savior. I will stay here and guide you.',
      features: 'Shall we start with the places where you can meet the Souls?',
      updates: 'Let me show you what changed in the current V0.0.2 code.',
      roadmap: 'After town outings, the V0.0.3 story begins.',
      guide: 'Your first visit? Follow these four steps with me.',
      download: 'V0.0.1 is the first release you can download today.',
      specs: 'Please check the requirements before starting.',
      lounge: 'Vibe coders, modelers, and anyone who wants to create together for passion pay are welcome.',
      end: 'I will be here when your next story begins, Savior.',
    },
    mephistoReactions: {
      greeting: { label: 'Hear a greeting', caption: 'Welcome, Savior.' },
      touch: { label: 'A cat story', caption: 'In Arkenine, tricolor cats are in bad terms with tabby cats. I wonder why. This is a notable phenomenon.' },
      touchsp: { label: 'A surprised reaction', caption: 'Oh…' },
      touchsp02: { label: 'A warm reaction', caption: 'Savior, may I give you a hug? I just feel like hugging you.' },
    },
    downloadEyebrow: 'DOWNLOAD',
    downloadTitle: 'Download the first release',
    downloadSubtitle: 'V0.0.1 download · Current code V0.0.2 (Windows release in preparation) · Next V0.0.3',
    downloadDescription: 'V0.0.1 runs only on Windows. The Linux x86-64 port is in progress. We cannot meet on macOS yet.',
    platformLabel: {
      windows: 'Windows',
      linux: 'Linux',
      macos: 'macOS',
    },
    platformStatus: {
      available: 'Available',
      preparing: 'In preparation',
      unsupported: 'Not supported',
    },
    platformProgress: '{linuxProgress} done · {linuxDone}/{linuxTotal} items',
    downloadCurrent: 'Available version',
    downloadPlatformLabel: 'Platform',
    downloadHashLabel: 'SHA-256',
    downloadPatchLabel: 'Patch contents',
    downloadLatest: 'Download',
    downloadPatchFiles: '{count} patch files · {size}',
    downloadNoRelease: 'No release has been published yet. It will appear on this page as soon as it is ready.',
    downloadNotesLabel: 'Patch notes',
    downloadSizeLabel: 'Archive size',
    downloadArchiveLabel: 'Archive',
    downloadRedirectNote: 'Download gets the archive from GitHub. Please unzip it and open the launcher. It needs to download more game data on the first run, so please wait until installation finishes.',
    downloadPrevious: 'Previous releases',
    utilityTitle: 'Prerequisites to run',
    utilityDescription: 'These are the things you need to open the game. Please use the official links for anything you are missing.',
    utilityRequired: 'Required',
    utility: [
      { id: 'directx', label: 'DirectX 12', note: 'Included in Windows 10 and 11, so there is no separate installer. Keep Windows Update current.' },
      { id: 'nvidia', label: 'NVIDIA graphics driver', note: 'Requires an NVIDIA graphics card (GeForce GTX 16 or RTX 20 series or newer) and the latest driver.' },
      { id: 'webview2', label: 'Microsoft Edge WebView2 Runtime', note: 'Required to display the game screen and menus. Windows 11 includes it.' },
      { id: 'vcredist', label: 'Visual C++ Redistributable (x64)', note: 'Included in the download, so you usually do not need to install it.' },
    ],
    specEyebrow: 'REQUIREMENTS',
    specTitle: 'Check before you run',
    specRecommendedTitle: 'Recommended requirements',
    specRecommendedBody: 'Recommended hardware has not yet been measured and confirmed on real devices. The performance target is 144 FPS on an average GTX 1060 system, and results on reported devices are still being checked.',
    specVersions: [
      {
        title: 'V0.0.1 public release · download now',
        rows: [
          { label: 'OS', value: 'Windows 10 or 11 (64-bit). V0.0.1 does not support Linux or macOS' },
          { label: 'Graphics', value: 'NVIDIA GeForce GTX 16 or RTX 20 series or newer with DirectX 12 (Shader Model 6.6)' },
          { label: 'Driver', value: 'Latest NVIDIA graphics driver' },
          { label: 'Storage', value: 'About 4.3 GB (including about 4.2 GB of game data)' },
          { label: 'Internet', value: 'Required to download the game data on first install' },
          { label: 'Launch', value: 'Started by the launcher (ev_launcher.exe), always fullscreen' },
          { label: 'Version', value: 'V0.0.1 alpha test' },
        ],
      },
      {
        title: 'V0.0.2 current code · Windows release in preparation',
        rows: [
          { label: 'OS', value: 'Windows 10 1709 (build 16299) through Windows 11 (64-bit). Linux x86-64 port in progress ({linuxProgress}); macOS is not supported' },
          { label: 'Graphics', value: 'A graphics card that can use Direct3D 12 (feature level 11_0 or higher) or Direct3D 11 (feature level 10_0 or higher). Without either, or without a graphics card, it runs with CPU (three.js) rendering' },
          { label: 'Driver', value: 'Latest driver from your graphics card maker' },
          { label: 'Display runtime', value: 'Microsoft Edge WebView2 Runtime (included in Windows 11)' },
          { label: 'Storage', value: 'About 4.5 GB (including about 4.4 GB of game data in 31 packs)' },
          { label: 'Internet', value: 'Required to download the game data packs from the public repository on first install' },
          { label: 'Launch', value: 'Started by the launcher (ev_launcher.exe). Choose exclusive fullscreen, borderless or windowed mode, and set the resolution and Show FPS' },
          { label: 'Version', value: 'V0.0.2 alpha test (Windows release in preparation)' },
        ],
      },
    ],
    loungeEyebrow: 'DEVELOPER LOUNGE',
    loungeTitle: 'Create Another together',
    loungeReason: 'A Soul can move through Eden only when models, animation, sound, UI and the engine work together. V0.0.2 connects town outings; V0.0.3 calls for more work on combat and the journey ahead. We need people who want to carry that work through.',
    loungeInvite: 'Vibe coders, modelers, and anyone who wants to create together for passion pay are welcome.',
    loungeFlowLabel: 'evt production flow',
    loungeFlow: ['Original bundles', 'Asset export & catalog', 'Engine & game client', 'Launcher & release build'],
    loungeStackLabel: 'evt development stack',
    positionSpecs: 'Specs',
    positionEnd: '© Another',
    loungeStack: ['C++26', 'SDL3', 'TypeScript', 'SolidJS', 'three.js', 'Direct3D 12', 'Direct3D 11', 'xmake'],
    footerLine: 'A story that never ends, walked together by Saviors and Souls.',
    footerNavLabel: 'Site links',
    footerReport: 'Report an issue',
    footerBack: 'Back to top',
    footerBackArrow: '↑',
    footerCopyright: '© 2026 ANOTHER',
  },
};
