import type { SoulRosterEntry } from '@evtp/type/soul/roster/SoulRosterEntry';

export const SOUL_ROSTER: readonly SoulRosterEntry[] = [
  { key: 'Rita', name: { ko: "리타", en: "Rita" } },
  { key: 'Rose', name: { ko: "로제", en: "Rose" } },
  { key: 'Sharing', name: { ko: "샤링", en: "Sharinne" } },
  { key: 'Ruri', name: { ko: "루리", en: "Ruri" } },
  { key: 'Alisha', name: { ko: "알리샤", en: "Alisha" } },
  { key: 'Lewayne', name: { ko: "르웨인", en: "Lewayne" } },
  { key: 'Nameless', name: { ko: "무명", en: "Nameless" } },
  { key: 'Karen', name: { ko: "카렌", en: "Karen" } },
  { key: 'Mephisto', name: { ko: "메피스토펠레스", en: "Mephistopheles" } },
  { key: 'Beleth', name: { ko: "벨레드", en: "Beleth" } },
  { key: 'Beatrice', name: { ko: "클레르", en: "Claire" } },
  { key: 'Aki', name: { ko: "아키", en: "Aki" } },
  { key: 'Jade', name: { ko: "제이드", en: "Jade" } },
  { key: 'Linzy', name: { ko: "린지", en: "Linzy" } },
  { key: 'Naomi', name: { ko: "나오미", en: "Naomi" } },
  { key: 'Lilith', name: { ko: "릴리트", en: "Lilith" } },
  { key: 'Catherine', name: { ko: "캐서린", en: "Catherine" } },
  { key: 'Catarina', name: { ko: "셰리", en: "Cherrie" } },
  { key: 'Dora', name: { ko: "도라", en: "Dora" } },
  { key: 'Jiho', name: { ko: "지호", en: "Jiho" } },
  { key: 'Hazel', name: { ko: "헤이즐", en: "Hazel" } },
  { key: 'Eileen', name: { ko: "에일린", en: "Eileen" } },
  { key: 'RoseCrimson', name: { ko: "로제(홍염)", en: "Rose (Prominence)" } },
  { key: 'JihoMir', name: { ko: "지호(미르)", en: "Jiho (Mir)" } },
  { key: 'CherrieRoman', name: { ko: "셰리(낭만)", en: "Cherrie (Romantic)" } },
  { key: 'Honglan', name: { ko: "홍란", en: "Honglan" } },
  { key: 'Sunny', name: { ko: "순이", en: "Soonie" } },
  { key: 'Aira', name: { ko: "아이라", en: "Aira" } },
  { key: 'Seeha', name: { ko: "시하", en: "Seeha" } },
  { key: 'Mica', name: { ko: "미카", en: "Mica" } },
  { key: 'Milia', name: { ko: "플린", en: "Flynn" } },
  { key: 'Tasha', name: { ko: "타샤", en: "Tasha" } },
  { key: 'Mia', name: { ko: "하루", en: "Haru" } },
  { key: 'Lute', name: { ko: "루테", en: "Lute" } },
  { key: 'Clara', name: { ko: "클라라", en: "Clara" } },
  { key: 'Xiaolian', name: { ko: "소연", en: "Xiaolian" } },
  { key: 'Sakuyo', name: { ko: "사쿠요", en: "Sakuyo" } },
  { key: 'Onyx', name: { ko: "오닉스", en: "Onyx" } },
  { key: 'SakuyoShin', name: { ko: "사쿠요(업화)", en: "Sakuyo (Inferno)" } },
  { key: 'HonglanCombat', name: { ko: "홍란(무쌍)", en: "Honglan (Peerless)" } },
  { key: 'HaruKamuy', name: { ko: "하루(카무이)", en: "Haru (Kamuy)" } },
  { key: 'Erika', name: { ko: "에리카", en: "Erika" } },
  { key: 'Leah', name: { ko: "르네", en: "Renee" } },
  { key: 'Talia', name: { ko: "탈리아", en: "Talia" } },
  { key: 'Kanna', name: { ko: "칸나", en: "Kanna" } },
  { key: 'Edith', name: { ko: "이디스", en: "Edith" } },
  { key: 'Nicole', name: { ko: "니콜", en: "Nicole" } },
  { key: 'Vivienne', name: { ko: "비비안", en: "Vivienne" } },
  { key: 'Miriam', name: { ko: "미리암", en: "Miriam" } },
  { key: 'Chloe', name: { ko: "클로이", en: "Chloe" } },
  { key: 'Nyah', name: { ko: "나이아", en: "Naiah" } },
  { key: 'Manon', name: { ko: "마농", en: "Manon" } },
  { key: 'Daphne', name: { ko: "다프네", en: "Daphne" } },
  { key: 'Dominique', name: { ko: "도미니크", en: "Dominique" } },
  { key: 'Wheri', name: { ko: "웨리", en: "Wheri" } },
  { key: 'ReneeSilver', name: { ko: "르네(백은)", en: "Renee (Argent)" } },
  { key: 'MiriamMirage', name: { ko: "미리암(잔영)", en: "Miriam (Afterimage)" } },
  { key: 'Laura', name: { ko: "라우라", en: "Laura" } },
  { key: 'Amelia', name: { ko: "비올레트", en: "Violette" } },
  { key: 'Olivia', name: { ko: "가넷", en: "Garnet" } },
  { key: 'Rebecca', name: { ko: "레베카", en: "Rebecca" } },
  { key: 'Melfice', name: { ko: "멜피스", en: "Melfice" } },
  { key: 'Blyce', name: { ko: "브라이스", en: "Bryce" } },
  { key: 'Prim', name: { ko: "프림", en: "Prim" } },
  { key: 'Jacqueline', name: { ko: "재클린", en: "Jacqueline" } },
  { key: 'Velanna', name: { ko: "벨라나", en: "Velanna" } },
  { key: 'Erusha', name: { ko: "에루샤", en: "Erusha" } },
  { key: 'Petra', name: { ko: "페트라", en: "Petra" } },
  { key: 'Nini', name: { ko: "니니", en: "Nini" } },
  { key: 'Otoha', name: { ko: "오토하", en: "Otoha" } },
  { key: 'Joanne', name: { ko: "조앤", en: "Joanne" } },
  { key: 'Sigrid', name: { ko: "시그리드", en: "Sigrid" } },
  { key: 'Weiss', name: { ko: "바이스", en: "Weiss" } },
  { key: 'PetraAwaken', name: { ko: "페트라(각혼)", en: "Petra (Awakened Soul)" } },
  { key: 'GarnetRapture', name: { ko: "가넷(열락)", en: "Garnet (Rapture)" } },
  { key: 'Claudia', name: { ko: "클라우디아", en: "Claudia" } },
  { key: 'Adrianne', name: { ko: "아드리안", en: "Adrianne" } },
  { key: 'YuriaQueen', name: { ko: "유리아", en: "Yuria" } },
  { key: 'Hanul', name: { ko: "한울", en: "Hanul" } },
  { key: 'Carnelian', name: { ko: "카넬리안", en: "Carnelian" } },
  { key: 'ClaudiaArchangel', name: { ko: "클라우디아(대천사)", en: "Claudia (Archangel)" } },
  { key: 'Larimar', name: { ko: "라리마", en: "Larimar" } },
  { key: 'Lizelotte', name: { ko: "리젤로테", en: "Lizelotte" } },
  { key: 'Oyome', name: { ko: "아야메", en: "Ayame" } },
  { key: 'Eve', name: { ko: "이브", en: "Eve" } },
  { key: 'Nia', name: { ko: "니아", en: "Nia" } },
  { key: 'AyameTsukuyomi', name: { ko: "아야메(츠쿠요미)", en: "Ayame (Tsukuyomi)" } },
  { key: 'CatherineBrave', name: { ko: "캐서린(광휘)", en: "Catherine (Radiance)" } },
  { key: 'LinzyThanatos', name: { ko: "린지(타나토스)", en: "Linzy (Thanatos)" } },
  { key: 'MephistoDawn', name: { ko: "메피스토펠레스(여명)", en: "Mephistopheles (Dawn)" } },
  { key: 'YuriaApollyon', name: { ko: "유리아(아폴리온)", en: "Yuria (Apollyon)" } },
  { key: 'Tokisaki', name: { ko: "토키사키 쿠루미", en: "Kurumi Tokisaki" } },
  { key: 'Yatogami', name: { ko: "야토가미 토카", en: "Tohka Yatogami" } },
];
