import type { DownloadUtilityTextEntry } from '@evtp/type/site/download/DownloadUtilityTextEntry';
import type { PlatformDownloadStatus } from '@evtp/type/site/download/PlatformDownload';
import type { FeatureEntry } from '@evtp/type/site/feature/FeatureEntry';
import type { GameFeatureEntry, GameFeatureStage } from '@evtp/type/site/feature/GameFeatureEntry';
import type { SpecVersion } from '@evtp/type/site/spec/SpecEntry';
import type { RoadmapNoticeEntry, RoadmapStage, UpdateEntry, UpdatePatchEntry } from '@evtp/type/site/update/UpdateEntry';
import type { SiteMephistoReactionId, SiteMephistoReactionText, SiteMephistoSection } from '@evtp/type/site/mephisto/SiteMephistoReaction';

export interface SiteText {
  brandName: string;
  brandFirst: string;
  brandSecond: string;
  metaDescription: string;
  navLabel: string;
  navGame: string;
  navUpdates: string;
  navRoadmap: string;
  navGuide: string;
  navDownload: string;
  navLanguage: string;
  navMenuOpen: string;
  navMenuClose: string;
  musicTitle: string;
  musicTrack: string;
  musicPlay: string;
  musicPause: string;
  musicMute: string;
  musicUnmute: string;
  musicSeek: string;
  musicUnavailable: string;
  localeKo: string;
  localeEn: string;
  skipToContent: string;
  heroEyebrow: string;
  heroTagline: string;
  heroDescription: string;
  heroPrimary: string;
  heroSecondary: string;
  heroScroll: string;
  heroDevNotice: string;
  heroDevLink: string;
  featureEyebrow: string;
  featureTitle: string;
  featureSubtitle: string;
  featureDescription: string;
  feature: readonly GameFeatureEntry[];
  featureStage: Readonly<Record<GameFeatureStage, string>>;
  devNoticeLabel: string;
  devNoticeTitle: string;
  devNoticeBody: string;
  devNoticeItems: readonly string[];
  updateEyebrow: string;
  updateTitle: string;
  updateSubtitle: string;
  updateDescription: string;
  updatePatchTitle: string;
  updatePatchCaution: string;
  updatePatchItems: readonly UpdatePatchEntry[];
  updateJump: string;
  updateEntries: readonly UpdateEntry[];
  roadmapEyebrow: string;
  roadmapTitle: string;
  roadmapSubtitle: string;
  roadmapDescription: string;
  roadmapCountUnit: string;
  roadmapIssuesSummary: string;
  roadmapNoticeTitle: string;
  roadmapNoticeDescription: string;
  roadmapJump: string;
  roadmapReport: string;
  issueFeedTitle: string;
  issueFeedDescription: string;
  issueFeedEmpty: string;
  issueFeedFilterLabel: string;
  issueFeedAll: string;
  issueFeedOpen: string;
  issueFeedClosed: string;
  issueFeedNumberLabel: string;
  issueFeedSubjectLabel: string;
  issueFeedStatusLabel: string;
  issueFeedDateLabel: string;
  issueFeedPagesLabel: string;
  issueFeedPrevious: string;
  issueFeedNext: string;
  roadmapStages: readonly RoadmapStage[];
  roadmapNotice: readonly RoadmapNoticeEntry[];
  guideEyebrow: string;
  guideTitle: string;
  guideSubtitle: string;
  guideDescription: string;
  guideSteps: readonly FeatureEntry[];
  mephistoSceneTitle: string;
  mephistoPanelTitle: string;
  mephistoLoading: string;
  mephistoUnavailable: string;
  mephistoVoiceUnavailable: string;
  mephistoVoiceNote: string;
  mephistoOpen: string;
  mephistoClose: string;
  mephistoDragHint: string;
  mephistoMessages: Readonly<Record<SiteMephistoSection, string>>;
  mephistoReactions: Readonly<Record<SiteMephistoReactionId, SiteMephistoReactionText>>;
  downloadEyebrow: string;
  downloadTitle: string;
  downloadSubtitle: string;
  downloadDescription: string;
  platformLabel: {
    windows: string;
    linux: string;
    macos: string;
  };
  platformStatus: Readonly<Record<PlatformDownloadStatus, string>>;
  platformProgress: string;
  downloadCurrent: string;
  downloadPlatformLabel: string;
  downloadHashLabel: string;
  downloadPatchLabel: string;
  downloadLatest: string;
  downloadPatchFiles: string;
  downloadNoRelease: string;
  downloadNotesLabel: string;
  downloadSizeLabel: string;
  downloadArchiveLabel: string;
  downloadRedirectNote: string;
  downloadPrevious: string;
  utilityTitle: string;
  utilityDescription: string;
  utilityRequired: string;
  utility: readonly DownloadUtilityTextEntry[];
  specEyebrow: string;
  specTitle: string;
  specRecommendedTitle: string;
  specRecommendedBody: string;
  specVersions: readonly SpecVersion[];
  loungeEyebrow: string;
  loungeTitle: string;
  loungeReason: string;
  loungeInvite: string;
  loungeFlowLabel: string;
  loungeFlow: readonly string[];
  loungeStackLabel: string;
  loungeStack: readonly string[];
  positionSpecs: string;
  positionEnd: string;
  footerLine: string;
  footerNavLabel: string;
  footerReport: string;
  footerBack: string;
  footerBackArrow: string;
  footerCopyright: string;
}
