import type { DownloadUtilityTextEntry } from '@evtp/type/site/download/DownloadUtilityTextEntry';
import type { FeatureEntry } from '@evtp/type/site/feature/FeatureEntry';
import type { SpecEntry } from '@evtp/type/site/spec/SpecEntry';

export interface SiteText {
  brandName: string;
  brandFirst: string;
  brandSecond: string;
  navLabel: string;
  navGame: string;
  navDownload: string;
  navLanguage: string;
  navMenuOpen: string;
  navMenuClose: string;
  localeKo: string;
  localeEn: string;
  skipToContent: string;
  heroEyebrow: string;
  heroTagline: string;
  heroDescription: string;
  heroPrimary: string;
  heroSecondary: string;
  heroScroll: string;
  featureEyebrow: string;
  featureTitle: string;
  featureDescription: string;
  feature: readonly FeatureEntry[];
  downloadEyebrow: string;
  downloadTitle: string;
  downloadDescription: string;
  platformLabel: {
    windows: string;
    linux: string;
    macos: string;
  };
  platformSupported: string;
  platformUnsupported: string;
  downloadCurrent: string;
  downloadLatest: string;
  downloadPatchFiles: string;
  downloadNoRelease: string;
  downloadNotesLabel: string;
  downloadSizeLabel: string;
  downloadArchiveLabel: string;
  downloadRedirectNote: string;
  downloadPrevious: string;
  utilityTitle: string;
  utilityDescription: string;
  utilityRequired: string;
  utility: readonly DownloadUtilityTextEntry[];
  specEyebrow: string;
  specTitle: string;
  spec: readonly SpecEntry[];
  footerLine: string;
  footerNavLabel: string;
  footerBack: string;
  footerBackArrow: string;
  footerCopyright: string;
}
